import { getTextFromMessageParts } from "@/lib/ai/message-text";
import { listBranches } from "@/lib/data/branches";
import type { CharacterBundle } from "@/lib/data/characters";
import { getCharacterBundle } from "@/lib/data/characters";
import { parseRow, type DatabaseClient } from "@/lib/data/shared";
import { listSnapshots } from "@/lib/data/snapshots";
import {
  listTurnsForThread,
  toModelContextMessages,
  toTranscriptMessages,
} from "@/lib/data/turns";
import type {
  ChatBranchRecord,
  ChatPinRecord,
  ChatTurnRecord,
  FantasiaUIMessage,
  MessageMetadata,
  ThreadRecord,
  ThreadStateSnapshot,
  TimelineEventRecord,
  TranscriptControl,
} from "@/lib/types";
import { z } from "zod";

const threadRecordSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  character_id: z.string().uuid(),
  connection_id: z.string().uuid(),
  model_id: z.string(),
  persona_id: z.string().uuid().nullable(),
  title: z.string(),
  is_title_autogenerated: z.boolean(),
  status: z.enum(["active", "archived"]),
  archived_at: z.string().nullable(),
  pinned_at: z.string().nullable(),
  created_at: z.string(),
  updated_at: z.string(),
});

const timelineRecordSchema = z.object({
  id: z.string().uuid(),
  thread_id: z.string().uuid(),
  branch_id: z.string().uuid(),
  turn_id: z.string().uuid().nullable(),
  title: z.string(),
  detail: z.string(),
  importance: z.number().int(),
  created_at: z.string(),
});

const pinRecordSchema = z.object({
  id: z.string().uuid(),
  thread_id: z.string().uuid(),
  branch_id: z.string().uuid(),
  turn_id: z.string().uuid().nullable(),
  body: z.string(),
  status: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
});

const threadSelect = [
  "id",
  "user_id",
  "character_id",
  "connection_id",
  "model_id",
  "persona_id",
  "title",
  "is_title_autogenerated",
  "status",
  "archived_at",
  "pinned_at",
  "created_at",
  "updated_at",
].join(", ");

const timelineSelect = [
  "id",
  "thread_id",
  "branch_id",
  "turn_id",
  "title",
  "detail",
  "importance",
  "created_at",
].join(", ");

const pinSelect = [
  "id",
  "thread_id",
  "branch_id",
  "turn_id",
  "body",
  "status",
  "created_at",
  "updated_at",
].join(", ");

export type ThreadGraphView = {
  thread: ThreadRecord;
  branches: ChatBranchRecord[];
  activeBranch: ChatBranchRecord;
  turns: ChatTurnRecord[];
  latestTurn: ChatTurnRecord | null;
  characterBundle: CharacterBundle | null;
  headSnapshot: ThreadStateSnapshot | null;
  headSnapshotPending: boolean;
  headSnapshotFailed: boolean;
  headSnapshotFailureMessage: string | null;
  timeline: TimelineEventRecord[];
  pins: ChatPinRecord[];
  canonicalMessages: FantasiaUIMessage[];
  modelContextMessages: FantasiaUIMessage[];
  controlsByMessageId: Record<string, TranscriptControl>;
};

export function createTextMessage(args: {
  id?: string;
  role: "user" | "assistant" | "system";
  text: string;
  metadata?: MessageMetadata;
}) {
  return {
    id: args.id ?? crypto.randomUUID(),
    role: args.role,
    parts: args.text
      ? [
          {
            type: "text" as const,
            text: args.text,
          },
        ]
      : [],
    metadata: args.metadata ?? {},
  } satisfies FantasiaUIMessage;
}

export function truncateMessageText(
  message: Pick<FantasiaUIMessage, "parts">,
  length = 120,
) {
  const text = getTextFromMessageParts(message.parts);
  if (text.length <= length) {
    return text;
  }

  return `${text.slice(0, length).trim()}...`;
}

export function buildTurnPath(
  turns: ChatTurnRecord[],
  headTurnId: string | null,
) {
  if (!headTurnId) {
    return [];
  }

  const turnsById = new Map(turns.map((turn) => [turn.id, turn]));
  const path: ChatTurnRecord[] = [];
  const seen = new Set<string>();
  let pointer: string | null = headTurnId;

  while (pointer) {
    if (seen.has(pointer)) {
      throw new Error("Detected a turn cycle while building the branch path.");
    }
    if (path.length >= 5000) {
      throw new Error("Branch history exceeded the supported depth limit.");
    }

    const turn = turnsById.get(pointer);
    if (!turn) {
      break;
    }

    seen.add(pointer);
    path.push(turn);
    pointer = turn.parent_turn_id;
  }

  return path.reverse();
}

async function getThread(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .select(threadSelect)
    .eq("user_id", userId)
    .eq("id", threadId)
    .maybeSingle();

  if (error) {
    throw error;
  }

  return data ? (parseRow(data, threadRecordSchema, "Thread") as ThreadRecord) : null;
}

async function listTimeline(
  supabase: DatabaseClient,
  threadId: string,
  branchId: string,
) {
  const { data, error } = await supabase
    .from("chat_timeline_events")
    .select(timelineSelect)
    .eq("thread_id", threadId)
    .eq("branch_id", branchId)
    .order("created_at", { ascending: false });

  if (error) {
    throw error;
  }

  return data?.map((row) =>
    parseRow(row, timelineRecordSchema, "Timeline event"),
  ) as TimelineEventRecord[] | undefined;
}

async function listPins(
  supabase: DatabaseClient,
  threadId: string,
  branchId: string,
) {
  const { data, error } = await supabase
    .from("chat_pins")
    .select(pinSelect)
    .eq("thread_id", threadId)
    .eq("branch_id", branchId)
    .eq("status", "active")
    .order("created_at", { ascending: false });

  if (error) {
    throw error;
  }

  return data?.map((row) =>
    parseRow(row, pinRecordSchema, "Pin"),
  ) as ChatPinRecord[] | undefined;
}

function resolveSnapshotState(
  reachableTurns: ChatTurnRecord[],
  latestTurn: ChatTurnRecord | null,
  snapshotsByTurnId: Map<string, ThreadStateSnapshot>,
) {
  const latestAvailableSnapshot =
    [...reachableTurns]
      .reverse()
      .map((turn) => snapshotsByTurnId.get(turn.id) ?? null)
      .find((snapshot) => snapshot !== null) ?? null;
  const headSnapshot = latestTurn
    ? snapshotsByTurnId.get(latestTurn.id) ?? latestAvailableSnapshot
    : latestAvailableSnapshot;

  return {
    headSnapshot,
    headSnapshotPending: false,
    headSnapshotFailed: false,
    headSnapshotFailureMessage: null,
  };
}

export function buildControlsByMessageId(turns: ChatTurnRecord[]) {
  const latestTurnId = turns.at(-1)?.id ?? null;
  const controlsByMessageId: Record<string, TranscriptControl> = {};

  for (const turn of turns) {
    if (turn.generation_status !== "committed") {
      continue;
    }

    controlsByMessageId[`${turn.id}:user`] = {
      turnId: turn.id,
      branchId: turn.branch_origin_id,
      canEdit: latestTurnId === turn.id,
      canRegenerate: false,
      canBranch: true,
      canRewind: true,
      canPin: true,
      canRate: false,
      feedbackRating: turn.feedback_rating,
    };

    controlsByMessageId[`${turn.id}:assistant`] = {
      turnId: turn.id,
      branchId: turn.branch_origin_id,
      canEdit: latestTurnId === turn.id,
      canRegenerate: latestTurnId === turn.id,
      canBranch: false,
      canRewind: false,
      canPin: true,
      canRate: true,
      feedbackRating: turn.feedback_rating,
    };
  }

  return controlsByMessageId;
}

export async function getThreadGraphView(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
): Promise<ThreadGraphView | null> {
  const thread = await getThread(supabase, userId, threadId);
  if (!thread) {
    return null;
  }

  const [branches, turns, characterBundle] = await Promise.all([
    listBranches(supabase, thread.id),
    listTurnsForThread(supabase, thread.id),
    getCharacterBundle(supabase, userId, thread.character_id),
  ]);

  const activeBranch = branches.find((branch) => branch.is_active) ?? branches[0] ?? null;
  if (!activeBranch) {
    return null;
  }

  const reachableTurns = buildTurnPath(turns, activeBranch.head_turn_id);
  const reachableTurnIds = new Set(reachableTurns.map((turn) => turn.id));

  const [snapshots, timelineRows, pinRows] = await Promise.all([
    listSnapshots(supabase, userId, thread.id),
    listTimeline(supabase, thread.id, activeBranch.id),
    listPins(supabase, thread.id, activeBranch.id),
  ]);

  const filteredTimeline = (timelineRows ?? []).filter(
    (event) => !event.turn_id || reachableTurnIds.has(event.turn_id),
  );
  const filteredPins = (pinRows ?? []).filter(
    (pin) => !pin.turn_id || reachableTurnIds.has(pin.turn_id),
  );
  const snapshotsByTurnId = new Map(
    snapshots.map((snapshot) => [snapshot.turn_id, snapshot]),
  );
  const latestTurn = reachableTurns.at(-1) ?? null;
  const {
    headSnapshot,
    headSnapshotPending,
    headSnapshotFailed,
    headSnapshotFailureMessage,
  } = resolveSnapshotState(reachableTurns, latestTurn, snapshotsByTurnId);

  const canonicalMessages = reachableTurns.flatMap((turn) => toTranscriptMessages(turn));
  const modelContextMessages = reachableTurns.flatMap((turn) =>
    toModelContextMessages(turn),
  );

  return {
    thread,
    branches,
    activeBranch,
    turns: reachableTurns,
    latestTurn,
    characterBundle,
    headSnapshot,
    headSnapshotPending,
    headSnapshotFailed,
    headSnapshotFailureMessage,
    timeline: filteredTimeline,
    pins: filteredPins,
    canonicalMessages,
    modelContextMessages,
    controlsByMessageId: buildControlsByMessageId(reachableTurns),
  };
}
