import { getTextFromMessageParts } from "@/lib/ai/message-text";
import { listBranches } from "@/lib/data/branches";
import type { CharacterBundle } from "@/lib/data/characters";
import { getCharacterBundle } from "@/lib/data/characters";
import { parseRow, type DatabaseClient } from "@/lib/data/shared";
import { listWorldSnapshots } from "@/lib/data/world-state";
import { materializeDurableSnapshot } from "@/lib/ai/state-materializer";
import {
  listTurnsForThread,
  toModelContextMessages,
  toTranscriptMessages,
} from "@/lib/data/turns";
import type {
  ChatBranchRecord,
  ChatPinRecord,
  ChatTurnRecord,
  ConnectionRecord,
  ContinuityInspectorView,
  DurableMemorySnapshot,
  FantasiaUIMessage,
  MessageMetadata,
  ThreadRecord,
  ThreadSettingsSlice,
  TimelineEventRecord,
  TranscriptControl,
  TurnSlicePatch,
  WorldSnapshotRecord,
} from "@/lib/types";
import { z } from "zod";

const threadRecordSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  character_id: z.string().uuid(),
  connection_id: z.string().uuid(),
  model_id: z.string(),
  persona_id: z.string().uuid().nullable(),
  brain_connection_id: z.string().uuid().nullable(),
  brain_model_id: z.string().nullable(),
  title: z.string(),
  is_title_autogenerated: z.boolean(),
  status: z.enum(["active", "archived"]),
  archived_at: z.string().nullable(),
  pinned_at: z.string().nullable(),
  created_at: z.string(),
  updated_at: z.string(),
});

const timelineRecordSchema = z.object({
  id: z.string().uuid(),
  thread_id: z.string().uuid(),
  branch_id: z.string().uuid(),
  turn_id: z.string().uuid().nullable(),
  title: z.string(),
  detail: z.string(),
  importance: z.number().int(),
  event_type: z.string(),
  affected_entity_ids: z.array(z.string()).default([]),
  affected_relationship_ids: z.array(z.string()).default([]),
  created_at: z.string(),
});

const pinRecordSchema = z.object({
  id: z.string().uuid(),
  thread_id: z.string().uuid(),
  branch_id: z.string().uuid(),
  turn_id: z.string().uuid().nullable(),
  body: z.string(),
  status: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
});

const threadSelect = [
  "id",
  "user_id",
  "character_id",
  "connection_id",
  "model_id",
  "persona_id",
  "brain_connection_id",
  "brain_model_id",
  "title",
  "is_title_autogenerated",
  "status",
  "archived_at",
  "pinned_at",
  "created_at",
  "updated_at",
].join(", ");

const timelineSelect = [
  "id",
  "thread_id",
  "branch_id",
  "turn_id",
  "title",
  "detail",
  "importance",
  "event_type",
  "affected_entity_ids",
  "affected_relationship_ids",
  "created_at",
].join(", ");

const pinSelect = [
  "id",
  "thread_id",
  "branch_id",
  "turn_id",
  "body",
  "status",
  "created_at",
  "updated_at",
].join(", ");

export type ThreadGraphView = {
  thread: ThreadRecord;
  branches: ChatBranchRecord[];
  activeBranch: ChatBranchRecord;
  turns: ChatTurnRecord[];
  latestTurn: ChatTurnRecord | null;
  characterBundle: CharacterBundle | null;
  headSnapshot: DurableMemorySnapshot | null;
  headSnapshotPending: boolean;
  headSnapshotFailed: boolean;
  headSnapshotFailureMessage: string | null;
  timeline: TimelineEventRecord[];
  pins: ChatPinRecord[];
  canonicalMessages: FantasiaUIMessage[];
  recentSceneMessages: FantasiaUIMessage[];
  controlsByMessageId: Record<string, TranscriptControl>;
};

export const RECENT_SCENE_TURN_WINDOW = 4;

export function createTextMessage(args: {
  id?: string;
  role: "user" | "assistant" | "system";
  text: string;
  metadata?: MessageMetadata;
}) {
  return {
    id: args.id ?? crypto.randomUUID(),
    role: args.role,
    parts: args.text
      ? [
          {
            type: "text" as const,
            text: args.text,
          },
        ]
      : [],
    metadata: args.metadata ?? {},
  } satisfies FantasiaUIMessage;
}

export function truncateMessageText(
  message: Pick<FantasiaUIMessage, "parts">,
  length = 120,
) {
  const text = getTextFromMessageParts(message.parts);
  if (text.length <= length) {
    return text;
  }

  return `${text.slice(0, length).trim()}...`;
}

export function buildTurnPath(
  turns: ChatTurnRecord[],
  headTurnId: string | null,
) {
  if (!headTurnId) {
    return [];
  }

  const turnsById = new Map(turns.map((turn) => [turn.id, turn]));
  const path: ChatTurnRecord[] = [];
  const seen = new Set<string>();
  let pointer: string | null = headTurnId;

  while (pointer) {
    if (seen.has(pointer)) {
      throw new Error("Detected a turn cycle while building the branch path.");
    }
    if (path.length >= 5000) {
      throw new Error("Branch history exceeded the supported depth limit.");
    }

    const turn = turnsById.get(pointer);
    if (!turn) {
      break;
    }

    seen.add(pointer);
    path.push(turn);
    pointer = turn.parent_turn_id;
  }

  return path.reverse();
}

export function buildRecentSceneMessages(
  turns: ChatTurnRecord[],
  turnWindow = RECENT_SCENE_TURN_WINDOW,
) {
  return turns
    .filter((turn) => turn.generation_status === "committed")
    .slice(-turnWindow)
    .flatMap((turn) => toModelContextMessages(turn));
}

async function getThread(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .select(threadSelect)
    .eq("user_id", userId)
    .eq("id", threadId)
    .maybeSingle();

  if (error) {
    throw error;
  }

  return data ? (parseRow(data, threadRecordSchema, "Thread") as ThreadRecord) : null;
}

async function listTimeline(
  supabase: DatabaseClient,
  threadId: string,
  branchId: string,
) {
  const { data, error } = await supabase
    .from("chat_timeline_events")
    .select(timelineSelect)
    .eq("thread_id", threadId)
    .eq("branch_id", branchId)
    .order("created_at", { ascending: false });

  if (error) {
    throw error;
  }

  return data?.map((row) =>
    parseRow(row, timelineRecordSchema, "Timeline event"),
  ) as TimelineEventRecord[] | undefined;
}

async function listPins(
  supabase: DatabaseClient,
  threadId: string,
  branchId: string,
) {
  const { data, error } = await supabase
    .from("chat_pins")
    .select(pinSelect)
    .eq("thread_id", threadId)
    .eq("branch_id", branchId)
    .eq("status", "active")
    .order("created_at", { ascending: false });

  if (error) {
    throw error;
  }

  return data?.map((row) =>
    parseRow(row, pinRecordSchema, "Pin"),
  ) as ChatPinRecord[] | undefined;
}

async function resolveSnapshotState(
  supabase: DatabaseClient,
  threadId: string,
  branchId: string,
  reachableTurns: ChatTurnRecord[],
  latestTurn: ChatTurnRecord | null,
  snapshotRecords: WorldSnapshotRecord[],
) {
  const snapshotsByTurnId = new Map(
    snapshotRecords.map((s) => [s.turn_id, s]),
  );
  const latestSnapshotRecord =
    [...reachableTurns]
      .reverse()
      .map((turn) => snapshotsByTurnId.get(turn.id) ?? null)
      .find((snapshot) => snapshot !== null) ?? null;
  const headSnapshotRecord = latestTurn
    ? snapshotsByTurnId.get(latestTurn.id) ?? latestSnapshotRecord
    : latestSnapshotRecord;

  let headSnapshot: DurableMemorySnapshot | null = null;
  let headSnapshotFailed = false;
  let headSnapshotFailureMessage: string | null = null;
  if (headSnapshotRecord) {
    try {
      headSnapshot = await materializeDurableSnapshot(
        supabase,
        threadId,
        branchId,
        headSnapshotRecord.turn_id,
        headSnapshotRecord,
      );
    } catch (error) {
      headSnapshotFailed = true;
      headSnapshotFailureMessage =
        error instanceof Error ? error.message : String(error);
      console.error("[read-model] Failed to materialize durable snapshot.", {
        threadId,
        turnId: headSnapshotRecord.turn_id,
        error: headSnapshotFailureMessage,
      });
    }
  }

  return {
    headSnapshot,
    headSnapshotPending: false,
    headSnapshotFailed,
    headSnapshotFailureMessage,
  };
}

export function buildControlsByMessageId(turns: ChatTurnRecord[]) {
  const latestTurnId = turns.at(-1)?.id ?? null;
  const controlsByMessageId: Record<string, TranscriptControl> = {};

  for (const turn of turns) {
    if (turn.generation_status !== "committed") {
      continue;
    }

    controlsByMessageId[`${turn.id}:user`] = {
      turnId: turn.id,
      branchId: turn.branch_origin_id,
      canEdit: latestTurnId === turn.id,
      canRegenerate: false,
      canBranch: true,
      canRewind: true,
      canPin: true,
      canRate: false,
      feedbackRating: turn.feedback_rating,
    };

    controlsByMessageId[`${turn.id}:assistant`] = {
      turnId: turn.id,
      branchId: turn.branch_origin_id,
      canEdit: latestTurnId === turn.id,
      canRegenerate: latestTurnId === turn.id,
      canBranch: false,
      canRewind: false,
      canPin: true,
      canRate: true,
      feedbackRating: turn.feedback_rating,
    };
  }

  return controlsByMessageId;
}

export async function getThreadGraphView(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
): Promise<ThreadGraphView | null> {
  const thread = await getThread(supabase, userId, threadId);
  if (!thread) {
    return null;
  }

  const [branches, turns, characterBundle] = await Promise.all([
    listBranches(supabase, thread.id),
    listTurnsForThread(supabase, thread.id),
    getCharacterBundle(supabase, userId, thread.character_id),
  ]);

  const activeBranch = branches.find((branch) => branch.is_active) ?? branches[0] ?? null;
  if (!activeBranch) {
    return null;
  }

  const reachableTurns = buildTurnPath(turns, activeBranch.head_turn_id);
  const reachableTurnIds = new Set(reachableTurns.map((turn) => turn.id));

  const [snapshots, timelineRows, pinRows] = await Promise.all([
    listWorldSnapshots(supabase, thread.id),
    listTimeline(supabase, thread.id, activeBranch.id),
    listPins(supabase, thread.id, activeBranch.id),
  ]);

  const filteredTimeline = (timelineRows ?? []).filter(
    (event) => !event.turn_id || reachableTurnIds.has(event.turn_id),
  );
  const filteredPins = (pinRows ?? []).filter(
    (pin) => !pin.turn_id || reachableTurnIds.has(pin.turn_id),
  );
  const latestTurn = reachableTurns.at(-1) ?? null;
  const {
    headSnapshot,
    headSnapshotPending,
    headSnapshotFailed,
    headSnapshotFailureMessage,
  } = await resolveSnapshotState(supabase, thread.id, activeBranch.id, reachableTurns, latestTurn, snapshots ?? []);

  const canonicalMessages = reachableTurns.flatMap((turn) => toTranscriptMessages(turn));
  const recentSceneMessages = buildRecentSceneMessages(reachableTurns);

  return {
    thread,
    branches,
    activeBranch,
    turns: reachableTurns,
    latestTurn,
    characterBundle,
    headSnapshot,
    headSnapshotPending,
    headSnapshotFailed,
    headSnapshotFailureMessage,
    timeline: filteredTimeline,
    pins: filteredPins,
    canonicalMessages,
    recentSceneMessages,
    controlsByMessageId: buildControlsByMessageId(reachableTurns),
  };
}

function truncateCopy(value: string, length: number) {
  if (value.length <= length) return value;
  return `${value.slice(0, length).trim()}...`;
}

/**
 * Build the continuity inspector payload (story summary, scene, entities,
 * relationships, pins, timeline, branch metadata) from a thread view. Shared by
 * the chat page and every mutation so read-your-writes returns an identical shape.
 */
export function buildInspectorView(view: ThreadGraphView): ContinuityInspectorView {
  const turnExcerptById = new Map(
    view.turns.map((turn) => {
      const transcript = [turn.user_input_text, turn.assistant_output_text ?? ""]
        .filter(Boolean)
        .join("\n");
      return [turn.id, transcript];
    }),
  );
  const parentBranch = view.branches.find(
    (branch) => branch.id === view.activeBranch.parent_branch_id,
  );
  const continuitySnapshot = view.headSnapshot;
  const continuityStatus = view.headSnapshotFailed
    ? {
        tone: "error" as const,
        title: "Continuity reconciliation failed",
        detail:
          view.headSnapshotFailureMessage ??
          "The active branch could not reconcile its latest turn. New turns stay blocked until you rewrite, regenerate, or rewind to a surviving turn.",
      }
    : view.headSnapshotPending
      ? {
          tone: "pending" as const,
          title: "Continuity reconciliation is still running",
          detail:
            "The latest turn has not produced a committed head snapshot yet. New turns stay blocked until reconciliation finishes.",
        }
      : null;

  return {
    continuityStatus,
    continuity: [
      {
        label: "Story summary",
        value:
          continuitySnapshot?.narrative_state.story_summary ||
          "No durable story summary has been written for this branch yet.",
        helper:
          "This is the whole-branch memory summary the next assistant turn receives as durable context.",
      },
      {
        label: "Current scene",
        value:
          continuitySnapshot?.narrative_state.scene_summary ||
          "No current-scene summary has been written for this branch yet.",
        helper:
          "This is the short scene-local memory that keeps the immediate situation sharp without replaying the whole chat.",
      },
      {
        label: "Last beat",
        value:
          continuitySnapshot?.narrative_state.last_turn_beat ||
          "No latest beat has been written for this branch yet.",
        helper:
          "This captures how the newest exchange changed the scene, so the next reply can build forward instead of repeating itself.",
      },
      {
        label: "Entities",
        value: continuitySnapshot?.entity_state.length
          ? continuitySnapshot.entity_state
              .map((e) => `• ${e.canonical_name} (${e.entity_type}) — ${e.primary_emotion} [${e.emotion_intensity}/10]`)
              .join("\n")
          : "No entities are currently tracked.",
        helper:
          "All characters, NPCs, creatures, and objects the engine is tracking, with their current emotional state.",
      },
      {
        label: "Relationships",
        value: continuitySnapshot?.relational_state.length
          ? continuitySnapshot.relational_state
              .map((r) => `• ${r.source_entity_name} → ${r.target_entity_name}: ${r.dynamic_status} (${r.relationship_type})`)
              .join("\n")
          : "No relationships are currently tracked.",
        helper:
          "Active relationships between entities with their current dynamic status.",
      },
      {
        label: "Current location",
        value: continuitySnapshot?.spatial_state.current_location
          ? `${continuitySnapshot.spatial_state.current_location.name}: ${continuitySnapshot.spatial_state.current_location.description}`
          : "No current location is set.",
        helper:
          "The user entity's current location in the world graph.",
      },
      {
        label: "Active threads",
        value:
          continuitySnapshot?.narrative_state.active_threads?.length
            ? continuitySnapshot.narrative_state.active_threads.map((t) => `• [${t.status}] ${t.objective}`).join("\n")
            : "No active threads are currently tracked on this branch.",
        helper:
          "These are the unresolved plot threads that are still alive and should be available to pull the next beat forward.",
      },
      {
        label: "Resolved threads",
        value: continuitySnapshot?.narrative_state.resolved_threads?.length
          ? continuitySnapshot.narrative_state.resolved_threads.map((item) => `• ${item}`).join("\n")
          : "No resolved threads are currently tracked yet.",
        helper:
          "Resolved threads are closed beats the runtime remembers as settled, so the assistant does not keep reopening them.",
      },
    ],
    pins: view.pins.map((pin) => ({
      id: pin.id,
      body: pin.body,
      createdAt: pin.created_at,
      sourceLabel: pin.turn_id ? "Pinned from transcript" : "Pinned manually",
      sourceExcerpt: pin.turn_id
        ? truncateCopy(turnExcerptById.get(pin.turn_id) ?? "Source turn is no longer on this branch.", 120)
        : "This pin was saved without a direct source message.",
    })),
    timeline: view.timeline.map((event) => ({
      id: event.id,
      title: event.title,
      detail: event.detail,
      importance: event.importance,
      createdAt: event.created_at,
    })),
    branch: {
      activeBranchId: view.activeBranch.id,
      activeBranchName: view.activeBranch.name,
      parentBranchName: parentBranch?.name ?? null,
      forkTurnId: view.activeBranch.fork_turn_id,
      headTurnId: view.activeBranch.head_turn_id,
      totalBranches: view.branches.length,
      totalTurns: view.turns.length,
    },
  };
}

/**
 * Build the switchable thread-settings slice. `connections` is used only to
 * resolve the human-readable label for the active chat connection.
 */
export function buildThreadSettingsSlice(
  view: ThreadGraphView,
  connections: ConnectionRecord[],
): ThreadSettingsSlice {
  const connection = connections.find((c) => c.id === view.thread.connection_id);
  return {
    model: {
      connectionId: view.thread.connection_id,
      modelId: view.thread.model_id,
      label: connection?.label ?? "",
    },
    personaId: view.thread.persona_id ?? "",
    brain: {
      connectionId: view.thread.brain_connection_id,
      modelId: view.thread.brain_model_id,
    },
    maxOutputTokens: view.thread.max_output_tokens,
  };
}

/**
 * Build the full read-your-writes slice returned by every chat mutation. Applying
 * it on the client is a wholesale replace of the reconcilable region — no diffing.
 */
export function buildTurnSlicePatch(
  view: ThreadGraphView,
  connections: ConnectionRecord[],
): TurnSlicePatch {
  return {
    headTurnId: view.activeBranch.head_turn_id,
    messages: view.canonicalMessages,
    controlsByMessageId: view.controlsByMessageId,
    activeBranch: view.activeBranch,
    branches: view.branches,
    inspectorView: buildInspectorView(view),
    settings: buildThreadSettingsSlice(view, connections),
  };
}
