import { describe, expect, it } from "vitest";
import {
  assertLatestTurnRewriteTarget,
  assertThreadReadyForLatestRewrite,
  assertThreadReadyForNewTurn,
  ThreadGenerationServiceError,
} from "@/lib/ai/thread-generation-service";
import type { ThreadGraphView } from "@/lib/threads/read-model";

function makeThreadView(
  overrides: Partial<ThreadGraphView> = {},
) {
  return {
    thread: {
      id: "thread-1",
      user_id: "user-1",
      character_id: "char-1",
      connection_id: "conn-1",
      model_id: "model-1",
      persona_id: "persona-1",
      title: "Thread",
      is_title_autogenerated: false,
      status: "active",
      archived_at: null,
      pinned_at: null,
      created_at: "",
      updated_at: "",
    },
    branches: [],
    activeBranch: {
      id: "branch-1",
      thread_id: "thread-1",
      name: "Main",
      parent_branch_id: null,
      fork_turn_id: null,
      head_turn_id: "turn-1",
      is_active: true,
      generation_locked: false,
      locked_by_turn_id: null,
      locked_at: null,
      created_by: "user-1",
      created_at: "",
      updated_at: "",
    },
    turns: [],
    latestTurn: {
      id: "turn-1",
      thread_id: "thread-1",
      branch_origin_id: "branch-1",
      parent_turn_id: null,
      user_input_text: "hello",
      user_input_payload: [],
      user_input_hidden: false,
      starter_seed: false,
      assistant_output_text: "hi",
      assistant_output_payload: [],
      generation_status: "committed",
      reserved_by_user_id: "user-1",
      assistant_provider: null,
      assistant_model: null,
      assistant_connection_label: null,
      finish_reason: null,
      total_tokens: null,
      prompt_tokens: null,
      completion_tokens: null,
      feedback_rating: null,
      generation_started_at: "",
      generation_finished_at: "",
      failure_code: null,
      failure_message: null,
      created_at: "",
      updated_at: "",
    },
    characterBundle: null,
    headSnapshot: null,
    headSnapshotPending: false,
    headSnapshotFailed: false,
    headSnapshotFailureMessage: null,
    timeline: [],
    pins: [],
    canonicalMessages: [],
    modelContextMessages: [],
    controlsByMessageId: {},
    ...overrides,
  } satisfies ThreadGraphView;
}

describe("thread generation guards", () => {
  it("allows a new turn even if the head snapshot is missing", () => {
    expect(() => assertThreadReadyForNewTurn(makeThreadView())).not.toThrow();
  });

  it("allows regenerate/edit even if the head snapshot is missing", () => {
    expect(() => assertThreadReadyForLatestRewrite(makeThreadView())).not.toThrow();
  });

  it("requires rewriting against the active branch head", () => {
    const latestTurn = assertLatestTurnRewriteTarget({
      threadView: makeThreadView(),
      branchId: "branch-1",
      expectedHeadTurnId: "turn-1",
    });

    expect(latestTurn.id).toBe("turn-1");
  });

  it("blocks rewrite requests when the active branch changed", () => {
    expect(() =>
      assertLatestTurnRewriteTarget({
        threadView: makeThreadView(),
        branchId: "branch-2",
        expectedHeadTurnId: "turn-1",
      }),
    ).toThrow(ThreadGenerationServiceError);
  });

  it("still blocks when the branch is generation-locked", () => {
    expect(() =>
      assertThreadReadyForNewTurn(
        makeThreadView({
          activeBranch: {
            ...makeThreadView().activeBranch,
            generation_locked: true,
          },
        }),
      ),
    ).toThrow(ThreadGenerationServiceError);
  });
});
