import { describe, it, expect, vi, beforeEach } from "vitest";
import { finalizeAssistantTurn } from "@/lib/ai/turn-finalizer";
import type { DatabaseClient } from "@/lib/data/shared";
import type { ThreadRecord } from "@/lib/types";

vi.mock("@/lib/data/checkpoints", () => ({
  createCheckpoint: vi.fn().mockResolvedValue({ id: "mock_ckpt_1" }),
}));
vi.mock("@/lib/data/messages", () => ({
  persistMessage: vi.fn((_sb, _t, msg) => Promise.resolve({ id: `persisted_${msg.id}`, content_text: "content" })),
}));
vi.mock("@/lib/data/branches", () => ({
  updateBranchHead: vi.fn().mockResolvedValue(null),
}));
vi.mock("@/lib/data/threads", () => ({
  maybeAutotitleThreadFromMessage: vi.fn().mockResolvedValue(null),
}));
vi.mock("@/lib/data/snapshots", () => ({
  saveSnapshot: vi.fn().mockResolvedValue(null),
}));
vi.mock("@/lib/data/timeline", () => ({
  insertTimelineEvent: vi.fn().mockResolvedValue(null),
}));
vi.mock("@/lib/ai/thread-engine", () => ({
  reconcileTurnState: vi.fn().mockResolvedValue({
    openLoops: [],
    resolvedLoops: [],
    scenarioState: "mock",
    relationshipState: "mock",
    rollingSummary: "mock",
    userFacts: [],
    narrativeHooks: [],
    sceneGoals: [],
    timelineEvent: null,
  }),
  buildSnapshotFromReconciliation: vi.fn().mockReturnValue({ version: 2 }),
}));

const mockSupabase = {} as DatabaseClient;

describe("finalizeAssistantTurn", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  const thread: ThreadRecord = {
    id: "thread_1",
    user_id: "user_1",
    title: "Test",
    connection_id: "conn_1",
    character_id: "char_1",
    model_id: "mod_1",
    persona_id: "persona_1",
    active_branch_id: "branch_1",
    archived_at: null,
    pinned_at: null,
    temperature_override: null,
    top_p_override: null,
    max_output_tokens_override: null,
    is_title_autogenerated: false,
    status: "active",
    created_at: "",
    updated_at: "",
  };

  const baseArgs = {
    supabase: mockSupabase,
    userId: "user_1",
    thread,
    branchId: "branch_1",
    parentCheckpointId: null,
    choiceGroupKey: "choice_1",
    previousSnapshot: null,
    connection: { id: "conn_1", user_id: "user_1", provider: "openrouter", label: "Mock", enabled: true, model_cache: [], health_status: "healthy", health_message: "", created_at: "", updated_at: "" } as any,
    character: {} as any,
    modelId: "mod_1",
    recentMessages: [],
  };

  it("throws if no existing user message id and no active user message is provided", async () => {
    await expect(
      finalizeAssistantTurn({
        ...baseArgs,
        userMessage: null,
        existingUserMessageId: "",
        assistantMessage: { id: "ast_1", role: "assistant", parts: [], metadata: {} },
      })
    ).rejects.toThrow("Cannot create a checkpoint without a persisted user message id.");
  });

  it("returns successfully orchestrated checkpoint, snapshot and stored messages on valid run", async () => {
    const result = await finalizeAssistantTurn({
      ...baseArgs,
      userMessage: { id: "user_msg_id", role: "user", parts: [], metadata: {} },
      assistantMessage: { id: "ast_msg_id", role: "assistant", parts: [], metadata: {} },
    });

    expect(result.checkpoint).toBeDefined();
    expect(result.checkpoint.id).toBe("mock_ckpt_1");
    expect(result.storedAssistant.id).toBe("persisted_ast_msg_id");
    expect(result.storedUser?.id).toBe("persisted_user_msg_id");
  });
});
