import { beforeEach, describe, expect, it, vi } from "vitest";

const {
  buildSnapshotFromReconciliationMock,
  createCheckpointMock,
  insertTimelineEventMock,
  maybeAutotitleThreadFromMessageMock,
  persistMessageMock,
  reconcileTurnStateMock,
  saveSnapshotMock,
  updateBranchHeadMock,
} = vi.hoisted(() => ({
  persistMessageMock: vi.fn(),
  createCheckpointMock: vi.fn(),
  updateBranchHeadMock: vi.fn(),
  maybeAutotitleThreadFromMessageMock: vi.fn(),
  reconcileTurnStateMock: vi.fn(),
  buildSnapshotFromReconciliationMock: vi.fn(),
  saveSnapshotMock: vi.fn(),
  insertTimelineEventMock: vi.fn(),
}));

vi.mock("@/lib/data/messages", () => ({
  persistMessage: persistMessageMock,
}));

vi.mock("@/lib/data/checkpoints", () => ({
  createCheckpoint: createCheckpointMock,
}));

vi.mock("@/lib/data/branches", () => ({
  updateBranchHead: updateBranchHeadMock,
}));

vi.mock("@/lib/data/threads", () => ({
  maybeAutotitleThreadFromMessage: maybeAutotitleThreadFromMessageMock,
}));

vi.mock("@/lib/ai/thread-engine", () => ({
  reconcileTurnState: reconcileTurnStateMock,
  buildSnapshotFromReconciliation: buildSnapshotFromReconciliationMock,
}));

vi.mock("@/lib/data/snapshots", () => ({
  saveSnapshot: saveSnapshotMock,
}));

vi.mock("@/lib/data/timeline", () => ({
  insertTimelineEvent: insertTimelineEventMock,
}));

import { finalizeAssistantTurn } from "@/lib/ai/turn-finalizer";

describe("finalizeAssistantTurn", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("commits continuity before moving the active branch head", async () => {
    const threadId = crypto.randomUUID();
    const branchId = crypto.randomUUID();
    const checkpointId = crypto.randomUUID();
    const previousSnapshot = {
      checkpoint_id: crypto.randomUUID(),
      thread_id: threadId,
      branch_id: branchId,
      based_on_snapshot_id: null,
      scenario_state: "Before",
      relationship_state: "Warm",
      rolling_summary: "Earlier beat",
      user_facts: [],
      open_loops: [],
      resolved_loops: [],
      narrative_hooks: [],
      scene_goals: [],
      version: 1,
      updated_at: new Date().toISOString(),
    };

    persistMessageMock
      .mockResolvedValueOnce({ id: "user-1", content_text: "Hi" })
      .mockResolvedValueOnce({ id: "assistant-1", content_text: "Hello" });
    createCheckpointMock.mockResolvedValue({
      id: checkpointId,
      branch_id: branchId,
      feedback_rating: null,
    });
    reconcileTurnStateMock.mockResolvedValue({
      scenarioState: "After",
      relationshipState: "Closer",
      rollingSummary: "Latest beat",
      userFacts: ["User likes rooftop talks"],
      openLoops: ["Why she knows too much"],
      sceneGoals: ["Keep her talking"],
      timelineEvent: {
        title: "Beat landed",
        detail: "The scene advanced.",
        importance: 3,
      },
    });
    buildSnapshotFromReconciliationMock.mockReturnValue({
      checkpoint_id: checkpointId,
      thread_id: threadId,
      branch_id: branchId,
      based_on_snapshot_id: previousSnapshot.checkpoint_id,
      scenario_state: "After",
      relationship_state: "Closer",
      rolling_summary: "Latest beat",
      user_facts: ["User likes rooftop talks"],
      open_loops: ["Why she knows too much"],
      resolved_loops: [],
      narrative_hooks: ["Explore why she knows too much"],
      scene_goals: ["Keep her talking"],
      version: 2,
      updated_at: new Date().toISOString(),
    });

    await finalizeAssistantTurn({
      supabase: {} as never,
      userId: crypto.randomUUID(),
      thread: {
        id: threadId,
        is_title_autogenerated: true,
      } as never,
      branchId,
      parentCheckpointId: previousSnapshot.checkpoint_id,
      userMessage: {
        id: "user-1",
        role: "user",
        parts: [{ type: "text", text: "Hi" }],
        metadata: {},
      } as never,
      assistantMessage: {
        id: "",
        role: "assistant",
        parts: [{ type: "text", text: "Hello" }],
        metadata: {},
      } as never,
      choiceGroupKey: "choice:test",
      previousSnapshot,
      connection: { id: crypto.randomUUID() } as never,
      character: { character: { name: "Gwen" } } as never,
      modelId: "mistral-medium-2505",
      recentMessages: [
        {
          id: "user-1",
          role: "user",
          parts: [{ type: "text", text: "Hi" }],
          metadata: {},
        },
        {
          id: "",
          role: "assistant",
          parts: [{ type: "text", text: "Hello" }],
          metadata: {},
        },
      ] as never,
    });

    expect(saveSnapshotMock).toHaveBeenCalledTimes(1);
    expect(updateBranchHeadMock).toHaveBeenCalledTimes(1);
    expect(saveSnapshotMock.mock.invocationCallOrder[0]).toBeLessThan(
      updateBranchHeadMock.mock.invocationCallOrder[0],
    );
    expect(insertTimelineEventMock).toHaveBeenCalledWith(
      {} as never,
      expect.objectContaining({
        thread_id: threadId,
        branch_id: branchId,
        checkpoint_id: checkpointId,
        source_message_id: "assistant-1",
        title: "Beat landed",
      }),
    );
    expect(maybeAutotitleThreadFromMessageMock).toHaveBeenCalledWith(
      {} as never,
      expect.any(String),
      expect.objectContaining({ id: threadId }),
      "Hi",
    );
  });
});
