import { beforeEach, describe, expect, it, vi } from "vitest";
import {
  finalizeAssistantTurn,
  rewriteCheckpointTurnInPlace,
} from "@/lib/ai/turn-finalizer";
import type { DatabaseClient } from "@/lib/data/shared";
import type { ChatCheckpointRecord, ThreadRecord } from "@/lib/types";

const rpcMock = vi.fn();

const supabase = {
  rpc: rpcMock,
} as unknown as DatabaseClient;

const thread: ThreadRecord = {
  id: crypto.randomUUID(),
  user_id: crypto.randomUUID(),
  title: "Test thread",
  connection_id: crypto.randomUUID(),
  character_id: crypto.randomUUID(),
  model_id: "model-1",
  persona_id: crypto.randomUUID(),
  active_branch_id: crypto.randomUUID(),
  archived_at: null,
  pinned_at: null,
  temperature_override: null,
  top_p_override: null,
  max_output_tokens_override: null,
  is_title_autogenerated: true,
  status: "active",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const checkpoint: ChatCheckpointRecord = {
  id: crypto.randomUUID(),
  thread_id: thread.id,
  branch_id: thread.active_branch_id!,
  parent_checkpoint_id: crypto.randomUUID(),
  user_message_id: crypto.randomUUID(),
  assistant_message_id: crypto.randomUUID(),
  choice_group_key: crypto.randomUUID(),
  feedback_rating: null,
  created_by: thread.user_id,
  created_at: new Date().toISOString(),
};

describe("turn-finalizer", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("finalizes a turn through the transactional RPC and enqueues reconcile work", async () => {
    rpcMock.mockResolvedValueOnce({
      data: {
        id: crypto.randomUUID(),
      },
      error: null,
    });

    const userMessage = {
      id: "user-msg-1",
      role: "user" as const,
      parts: [{ type: "text" as const, text: "Open with a secret." }],
      metadata: { createdAt: "2026-04-13T10:00:00.000Z" },
    };
    const assistantMessage = {
      id: "assistant-msg-1",
      role: "assistant" as const,
      parts: [{ type: "text" as const, text: "She leans in and lowers her voice." }],
      metadata: { model: "model-1" },
    };

    const result = await finalizeAssistantTurn({
      supabase,
      userId: thread.user_id,
      thread,
      branchId: thread.active_branch_id!,
      parentCheckpointId: null,
      userMessage,
      assistantMessage,
      choiceGroupKey: "choice-1",
      recentMessages: [userMessage, assistantMessage],
    });

    expect(rpcMock).toHaveBeenCalledWith(
      "finalize_turn_and_enqueue_reconcile",
      expect.objectContaining({
        p_thread_id: thread.id,
        p_user_id: thread.user_id,
        p_branch_id: thread.active_branch_id,
        p_parent_checkpoint_id: null,
        p_choice_group_key: "choice-1",
        p_user_message_id: "user-msg-1",
        p_user_message_content_text: "Open with a secret.",
        p_assistant_message_id: "assistant-msg-1",
        p_assistant_message_content_text: "She leans in and lowers her voice.",
        p_autotitle_text: "Open with a secret.",
        p_reconcile_payload: expect.objectContaining({
          threadId: thread.id,
          branchId: thread.active_branch_id,
          checkpointId: "",
          previousCheckpointId: null,
          connectionId: thread.connection_id,
          modelId: thread.model_id,
          characterId: thread.character_id,
          personaId: thread.persona_id,
          recentMessageIds: ["user-msg-1", "assistant-msg-1"],
        }),
      }),
    );
    expect(result.checkpoint.id).toBeDefined();
    expect(result.storedUser.id).toBe("user-msg-1");
    expect(result.storedAssistant.id).toBe("assistant-msg-1");
  });

  it("rewrites an existing checkpoint in place and clears user fields when not provided", async () => {
    rpcMock.mockResolvedValueOnce({
      data: checkpoint,
      error: null,
    });

    const assistantMessage = {
      id: checkpoint.assistant_message_id,
      role: "assistant" as const,
      parts: [{ type: "text" as const, text: "The reply was rebuilt in place." }],
      metadata: { model: "model-1" },
    };

    const result = await rewriteCheckpointTurnInPlace({
      supabase,
      userId: thread.user_id,
      thread,
      branchId: checkpoint.branch_id,
      checkpoint,
      assistantMessage,
      recentMessages: [assistantMessage],
    });

    expect(rpcMock).toHaveBeenCalledWith(
      "rewrite_latest_turn_in_place",
      expect.objectContaining({
        p_thread_id: thread.id,
        p_user_id: thread.user_id,
        p_branch_id: checkpoint.branch_id,
        p_checkpoint_id: checkpoint.id,
        p_user_message_id: null,
        p_user_message_parts: null,
        p_user_message_content_text: null,
        p_user_message_metadata: null,
        p_assistant_message_id: checkpoint.assistant_message_id,
        p_assistant_message_content_text: "The reply was rebuilt in place.",
        p_autotitle_text: null,
        p_reconcile_payload: expect.objectContaining({
          checkpointId: checkpoint.id,
          previousCheckpointId: checkpoint.parent_checkpoint_id,
          recentMessageIds: [checkpoint.assistant_message_id],
        }),
      }),
    );
    expect(result.checkpoint).toEqual(checkpoint);
    expect(result.storedUser).toBeNull();
    expect(result.storedAssistant.id).toBe(checkpoint.assistant_message_id);
  });
});
