import { beforeEach, describe, expect, it, vi } from "vitest";
import { rateCheckpoint } from "@/lib/data/checkpoints";

function createOwnedThread(userId: string, threadId: string) {
  return {
    id: threadId,
    user_id: userId,
    character_id: crypto.randomUUID(),
    connection_id: crypto.randomUUID(),
    model_id: "model",
    persona_id: null,
    active_branch_id: crypto.randomUUID(),
    title: "Thread",
    is_title_autogenerated: true,
    status: "active",
    archived_at: null,
    pinned_at: null,
    temperature_override: null,
    top_p_override: null,
    max_output_tokens_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };
}

describe("rateCheckpoint", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("verifies thread ownership and scopes the update to the thread", async () => {
    const userId = crypto.randomUUID();
    const threadId = crypto.randomUUID();
    const checkpointId = crypto.randomUUID();
    const eqCalls: Array<[string, unknown]> = [];

    const supabase = {
      from: vi.fn((table: string) => {
        if (table === "chat_threads") {
          return {
            select: vi.fn(() => ({
              eq: vi.fn((column: string, value: unknown) => {
                eqCalls.push([column, value]);
                return {
                  eq: vi.fn((nestedColumn: string, nestedValue: unknown) => {
                    eqCalls.push([nestedColumn, nestedValue]);
                    return {
                      maybeSingle: vi.fn().mockResolvedValue({
                        data: createOwnedThread(userId, threadId),
                        error: null,
                      }),
                    };
                  }),
                };
              }),
            })),
          };
        }

        if (table === "chat_checkpoints") {
          return {
            update: vi.fn(() => ({
              eq: vi.fn((column: string, value: unknown) => {
                eqCalls.push([column, value]);
                return {
                  eq: vi.fn((nestedColumn: string, nestedValue: unknown) => {
                    eqCalls.push([nestedColumn, nestedValue]);
                    return {
                      select: vi.fn(() => ({
                        single: vi.fn().mockResolvedValue({
                          data: {
                            id: checkpointId,
                            thread_id: threadId,
                            branch_id: crypto.randomUUID(),
                            parent_checkpoint_id: null,
                            user_message_id: "user-1",
                            assistant_message_id: "assistant-1",
                            choice_group_key: "group-1",
                            feedback_rating: 4,
                            created_by: userId,
                            created_at: new Date().toISOString(),
                          },
                          error: null,
                        }),
                      })),
                    };
                  }),
                };
              }),
            })),
          };
        }

        throw new Error(`Unexpected table ${table}`);
      }),
    } as never;

    await rateCheckpoint(supabase, userId, threadId, checkpointId, 4);

    expect(eqCalls).toContainEqual(["id", checkpointId]);
    expect(eqCalls).toContainEqual(["thread_id", threadId]);
  });

  it("rejects checkpoint updates for threads the caller does not own", async () => {
    const supabase = {
      from: vi.fn(() => ({
        select: vi.fn(() => ({
          eq: vi.fn(() => ({
            eq: vi.fn(() => ({
              maybeSingle: vi.fn().mockResolvedValue({ data: null, error: null }),
            })),
          })),
        })),
      })),
    } as never;

    await expect(
      rateCheckpoint(supabase, crypto.randomUUID(), crypto.randomUUID(), crypto.randomUUID(), 3),
    ).rejects.toThrow("Thread not found.");
  });
});
