import { z } from "zod";
import { parseRow, parseRows, type DatabaseClient } from "@/lib/data/shared";
import type {
  ConnectionRecord,
  ThreadListItem,
  ThreadRecord,
} from "@/lib/types";

const threadRecordSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  character_id: z.string().uuid(),
  connection_id: z.string().uuid(),
  model_id: z.string(),
  persona_id: z.string().uuid().nullable(),
  title: z.string(),
  is_title_autogenerated: z.boolean(),
  status: z.enum(["active", "archived"]),
  archived_at: z.string().nullable(),
  pinned_at: z.string().nullable(),
  created_at: z.string(),
  updated_at: z.string(),
});

const threadSelect = [
  "id",
  "user_id",
  "character_id",
  "connection_id",
  "model_id",
  "persona_id",
  "title",
  "is_title_autogenerated",
  "status",
  "archived_at",
  "pinned_at",
  "created_at",
  "updated_at",
].join(", ");

const threadLibraryRowSchema = threadRecordSchema.extend({
  characters: z.object({ name: z.string() }).nullable(),
  user_personas: z.object({ name: z.string() }).nullable(),
});

function normalizeThread(value: unknown, label = "Thread") {
  return parseRow(value, threadRecordSchema, label) as ThreadRecord;
}

async function loadActiveBranchMap(
  supabase: DatabaseClient,
  threadIds: string[],
) {
  if (!threadIds.length) {
    return new Map<string, string>();
  }

  const { data, error } = await supabase
    .from("chat_branches")
    .select("id, thread_id")
    .in("thread_id", threadIds)
    .eq("is_active", true);

  if (error) {
    throw error;
  }

  return new Map((data ?? []).map((row) => [row.thread_id, row.id]));
}

async function loadThreadLibraryRows(
  supabase: DatabaseClient,
  userId: string,
  options?: {
    query?: string;
    status?: "active" | "archived" | "all";
    limit?: number;
  },
) {
  let query = supabase
    .from("chat_threads")
    .select(
      `${threadSelect}, characters(name), user_personas(name)`,
    )
    .eq("user_id", userId)
    .order("pinned_at", { ascending: false, nullsFirst: false })
    .order("updated_at", { ascending: false });

  if (options?.status && options.status !== "all") {
    query = query.eq("status", options.status);
  }

  if (options?.limit) {
    query = query.limit(options.limit);
  }

  const { data, error } = await query;
  if (error) {
    throw error;
  }

  const parsed = parseRows(data ?? [], threadLibraryRowSchema, "Thread library rows");
  const filtered = options?.query?.trim()
    ? parsed.filter((row) => {
        const haystack = [
          row.title,
          row.characters?.name ?? "",
          row.user_personas?.name ?? "",
        ]
          .join(" ")
          .toLowerCase();
        return haystack.includes(options.query!.trim().toLowerCase());
      })
    : parsed;

  const activeBranchByThreadId = await loadActiveBranchMap(
    supabase,
    filtered.map((row) => row.id),
  );

  return filtered.map((row) => ({
    ...row,
    character_name: row.characters?.name ?? null,
    persona_name: row.user_personas?.name ?? null,
    active_branch_id: activeBranchByThreadId.get(row.id) ?? null,
  })) satisfies ThreadListItem[];
}

export async function listThreads(supabase: DatabaseClient, userId: string) {
  return listThreadItems(supabase, userId, { status: "active" });
}

export async function listRecentThreads(
  supabase: DatabaseClient,
  userId: string,
  limit = 6,
) {
  return loadThreadLibraryRows(supabase, userId, {
    status: "active",
    limit,
  });
}

export async function listThreadItems(
  supabase: DatabaseClient,
  userId: string,
  options?: {
    query?: string;
    status?: "active" | "archived" | "all";
  },
) {
  return loadThreadLibraryRows(supabase, userId, options);
}

export async function getThread(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .select(threadSelect)
    .eq("user_id", userId)
    .eq("id", threadId)
    .maybeSingle();

  if (error) {
    throw error;
  }

  return data ? normalizeThread(data) : null;
}

export async function createThread(
  supabase: DatabaseClient,
  userId: string,
  args: {
    characterId: string;
    connection: ConnectionRecord;
    modelId: string;
    title: string;
    personaId: string;
  },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .insert({
      user_id: userId,
      character_id: args.characterId,
      connection_id: args.connection.id,
      model_id: args.modelId,
      persona_id: args.personaId,
      title: args.title,
      is_title_autogenerated: true,
    })
    .select(threadSelect)
    .single();

  if (error) {
    throw error;
  }

  const thread = normalizeThread(data, "Created thread");

  try {
    const { error: branchError } = await supabase.from("chat_branches").insert({
      thread_id: thread.id,
      name: "Main",
      is_active: true,
      created_by: userId,
    });

    if (branchError) {
      throw branchError;
    }
  } catch (branchError) {
    await supabase
      .from("chat_threads")
      .delete()
      .eq("id", thread.id)
      .eq("user_id", userId);
    throw branchError;
  }

  return thread;
}

export async function updateThreadModel(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; connectionId: string; modelId: string },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({
      connection_id: args.connectionId,
      model_id: args.modelId,
      updated_at: new Date().toISOString(),
    })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) {
    throw error;
  }

  return normalizeThread(data, "Updated thread model");
}

export async function updateThreadPersona(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; personaId: string },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({
      persona_id: args.personaId,
      updated_at: new Date().toISOString(),
    })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) {
    throw error;
  }

  return normalizeThread(data, "Updated thread persona");
}

export async function switchActiveBranch(
  supabase: DatabaseClient,
  _userId: string,
  args: { threadId: string; branchId: string },
) {
  const { error } = await supabase.rpc("activate_branch", {
    p_thread_id: args.threadId,
    p_branch_id: args.branchId,
  });

  if (error) {
    throw error;
  }

  return getThread(supabase, _userId, args.threadId);
}

export async function renameThread(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
  title: string,
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({
      title,
      is_title_autogenerated: false,
      updated_at: new Date().toISOString(),
    })
    .eq("id", threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) {
    throw error;
  }

  return normalizeThread(data, "Renamed thread");
}

export async function updateThreadPinnedState(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; pinned: boolean },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({
      pinned_at: args.pinned ? new Date().toISOString() : null,
      updated_at: new Date().toISOString(),
    })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) {
    throw error;
  }

  return normalizeThread(data, "Pinned thread");
}

export async function updateThreadStatus(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; status: ThreadRecord["status"] },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({
      status: args.status,
      archived_at: args.status === "archived" ? new Date().toISOString() : null,
      updated_at: new Date().toISOString(),
    })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) {
    throw error;
  }

  return normalizeThread(data, "Updated thread status");
}

export async function deleteThread(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
) {
  const { error } = await supabase
    .from("chat_threads")
    .delete()
    .eq("id", threadId)
    .eq("user_id", userId);

  if (error) {
    throw error;
  }
}
