import { getTextFromMessageParts } from "@/lib/ai/message-text";
import { listBranches } from "@/lib/data/branches";
import { listCheckpoints } from "@/lib/data/checkpoints";
import { castRow, castRows, type DatabaseClient } from "@/lib/data/shared";
import { getMessagesByIds, toUIMessages } from "@/lib/data/messages";
import { getLatestReconcileJobForCheckpoint } from "@/lib/data/jobs";
import { listPins } from "@/lib/data/pins";
import { listSnapshotsByCheckpointIds } from "@/lib/data/snapshots";
import { listTimeline } from "@/lib/data/timeline";
import type {
  BackgroundJobRecord,
  ChatBranchRecord,
  ChatCheckpointRecord,
  ConnectionRecord,
  FantasiaUIMessage,
  MessageMetadata,
  StoredMessageRecord,
  ThreadListItem,
  ThreadRecord,
  ThreadStateSnapshot,
  TranscriptControl,
} from "@/lib/types";

export const threadSelect = [
  "id",
  "user_id",
  "character_id",
  "connection_id",
  "model_id",
  "persona_id",
  "active_branch_id",
  "title",
  "is_title_autogenerated",
  "status",
  "archived_at",
  "pinned_at",
  "temperature_override",
  "top_p_override",
  "max_output_tokens_override",
  "created_at",
  "updated_at",
].join(", ");

const threadListSelect = `${threadSelect}, characters(name), user_personas(name)`;

export type ThreadGraphView = {
  thread: ThreadRecord;
  branches: ChatBranchRecord[];
  activeBranch: ChatBranchRecord;
  checkpoints: ChatCheckpointRecord[];
  latestCheckpoint: ChatCheckpointRecord | null;
  headSnapshot: ThreadStateSnapshot | null;
  resolvedSnapshot: ThreadStateSnapshot | null;
  headSnapshotPending: boolean;
  headSnapshotFailed: boolean;
  headSnapshotFailureMessage: string | null;
  timeline: Awaited<ReturnType<typeof listTimeline>>;
  pins: Awaited<ReturnType<typeof listPins>>;
  canonicalMessages: FantasiaUIMessage[];
  modelContextMessages: FantasiaUIMessage[];
  controlsByMessageId: Record<string, TranscriptControl>;
};

export function resolveSnapshotState(
  checkpoints: ChatCheckpointRecord[],
  snapshotsByCheckpointId: Map<string, ThreadStateSnapshot>,
  latestReconcileJob?: Pick<BackgroundJobRecord, "status" | "last_error"> | null,
) {
  const latestCheckpoint = checkpoints.at(-1) ?? null;
  const headSnapshot = latestCheckpoint
    ? snapshotsByCheckpointId.get(latestCheckpoint.id) ?? null
    : null;
  const resolvedSnapshot =
    headSnapshot ??
    [...checkpoints]
      .reverse()
      .map((checkpoint) => snapshotsByCheckpointId.get(checkpoint.id) ?? null)
      .find((snapshot): snapshot is ThreadStateSnapshot => Boolean(snapshot)) ??
    null;
  const headSnapshotFailed = Boolean(
    latestCheckpoint &&
      !headSnapshot &&
      latestReconcileJob?.status === "failed",
  );

  return {
    headSnapshot,
    resolvedSnapshot,
    headSnapshotPending: Boolean(latestCheckpoint && !headSnapshot && !headSnapshotFailed),
    headSnapshotFailed,
    headSnapshotFailureMessage: headSnapshotFailed
      ? latestReconcileJob?.last_error ?? "Continuity reconciliation failed for the branch head."
      : null,
  };
}

function sortThreads<T extends ThreadRecord>(threads: T[]) {
  return [...threads].sort((left, right) => {
    const leftPinned = left.pinned_at ? new Date(left.pinned_at).getTime() : 0;
    const rightPinned = right.pinned_at ? new Date(right.pinned_at).getTime() : 0;
    if (leftPinned !== rightPinned) return rightPinned - leftPinned;
    return new Date(right.updated_at).getTime() - new Date(left.updated_at).getTime();
  });
}

export async function listThreads(supabase: DatabaseClient, userId: string) {
  return listThreadItems(supabase, userId, { status: "active" });
}

export async function listThreadItems(
  supabase: DatabaseClient,
  userId: string,
  options?: {
    query?: string;
    status?: "active" | "archived" | "all";
  },
) {
  const status = options?.status ?? "all";
  let queryBuilder = supabase
    .from("chat_threads")
    .select(threadListSelect)
    .eq("user_id", userId)
    .not("active_branch_id", "is", null)
    .order("updated_at", { ascending: false });

  if (status !== "all") {
    queryBuilder = queryBuilder.eq("status", status);
  }

  const { data, error } = await queryBuilder;

  if (error) throw error;
  const raw = castRows<ThreadListItem>(data, "Thread list items");
  const query = options?.query?.trim().toLowerCase() ?? "";

  return sortThreads(
    raw.filter((thread) => {
      if (!query) return true;
      return [thread.title, thread.characters?.name, thread.user_personas?.name]
        .filter(Boolean)
        .some((value) => value!.toLowerCase().includes(query));
    }),
  );
}

export async function getThread(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .select(threadSelect)
    .eq("user_id", userId)
    .eq("id", threadId)
    .maybeSingle();

  if (error) throw error;
  return data ? castRow<ThreadRecord>(data) : null;
}

export async function createThread(
  supabase: DatabaseClient,
  userId: string,
  args: {
    characterId: string;
    connection: ConnectionRecord;
    modelId: string;
    title: string;
    personaId: string;
  },
) {
  const { data, error } = await supabase.rpc("create_thread_with_main_branch", {
    p_user_id: userId,
    p_character_id: args.characterId,
    p_connection_id: args.connection.id,
    p_model_id: args.modelId,
    p_persona_id: args.personaId,
    p_title: args.title,
  });

  if (error) throw error;
  return castRow<ThreadRecord>(data, "Created thread");
}

export async function updateThreadModel(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; connectionId: string; modelId: string },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({
      connection_id: args.connectionId,
      model_id: args.modelId,
    })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) throw error;
  return castRow<ThreadRecord>(data);
}

export async function updateThreadPersona(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; personaId: string },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({ persona_id: args.personaId })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) throw error;
  return castRow<ThreadRecord>(data);
}

export async function switchActiveBranch(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; branchId: string },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({ active_branch_id: args.branchId })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) throw error;
  return castRow<ThreadRecord>(data);
}

export async function renameThread(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
  title: string,
) {
  const { error } = await supabase
    .from("chat_threads")
    .update({
      title,
      is_title_autogenerated: false,
      updated_at: new Date().toISOString(),
    })
    .eq("id", threadId)
    .eq("user_id", userId);

  if (error) throw error;
  return getThread(supabase, userId, threadId);
}

export async function maybeAutotitleThreadFromMessage(
  supabase: DatabaseClient,
  userId: string,
  thread: ThreadRecord,
  text: string,
) {
  if (!thread.is_title_autogenerated) {
    return thread;
  }

  const nextTitle = text.trim().slice(0, 60).trim();
  if (!nextTitle) {
    return thread;
  }

  const { data, error } = await supabase
    .from("chat_threads")
    .update({
      title: nextTitle,
      is_title_autogenerated: false,
      updated_at: new Date().toISOString(),
    })
    .eq("id", thread.id)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) throw error;
  return castRow<ThreadRecord>(data);
}

export async function updateThreadPinnedState(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; pinned: boolean },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({
      pinned_at: args.pinned ? new Date().toISOString() : null,
      updated_at: new Date().toISOString(),
    })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) throw error;
  return castRow<ThreadRecord>(data);
}

export async function updateThreadStatus(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; status: ThreadRecord["status"] },
) {
  const archivedAt = args.status === "archived" ? new Date().toISOString() : null;
  const { data, error } = await supabase
    .from("chat_threads")
    .update({
      status: args.status,
      archived_at: archivedAt,
      updated_at: new Date().toISOString(),
    })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) throw error;
  return castRow<ThreadRecord>(data);
}

export async function deleteThread(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
) {
  const { error } = await supabase
    .from("chat_threads")
    .delete()
    .eq("id", threadId)
    .eq("user_id", userId);

  if (error) throw error;
}

export async function getThreadGraphView(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
): Promise<ThreadGraphView | null> {
  const thread = await getThread(supabase, userId, threadId);
  if (!thread || !thread.active_branch_id) return null;

  const [branches, checkpoints] = await Promise.all([
    listBranches(supabase, userId, threadId),
    listCheckpoints(supabase, userId, threadId),
  ]);

  const activeBranch = branches.find((branch) => branch.id === thread.active_branch_id);
  if (!activeBranch) return null;

  const checkpointPath = buildCheckpointPath(checkpoints, activeBranch.head_checkpoint_id);
  const latestCheckpoint = checkpointPath.at(-1) ?? null;
  const messageIds = checkpointPath.flatMap((checkpoint) => [
    checkpoint.user_message_id,
    checkpoint.assistant_message_id,
  ]);
  const checkpointIds = checkpointPath.map((checkpoint) => checkpoint.id);
  const [messages, snapshots, latestReconcileJob] = await Promise.all([
    getMessagesByIds(supabase, messageIds),
    listSnapshotsByCheckpointIds(supabase, checkpointIds),
    latestCheckpoint
      ? getLatestReconcileJobForCheckpoint(supabase, latestCheckpoint.id)
      : Promise.resolve(null),
  ]);
  const messagesById = new Map(messages.map((message) => [message.id, message]));
  const snapshotsByCheckpointId = new Map(
    snapshots.map((snapshot) => [snapshot.checkpoint_id, snapshot]),
  );

  const canonicalStoredMessages: StoredMessageRecord[] = [];
  const controlsByMessageId: Record<string, TranscriptControl> = {};

  checkpointPath.forEach((checkpoint, index) => {
    const userMessage = messagesById.get(checkpoint.user_message_id);
    const assistantMessage = messagesById.get(checkpoint.assistant_message_id);
    if (!userMessage || !assistantMessage) return;

    const isLatest = index === checkpointPath.length - 1;

    if (!userMessage.metadata?.hiddenFromTranscript) {
      controlsByMessageId[userMessage.id] = {
        checkpointId: checkpoint.id,
        branchId: checkpoint.branch_id,
        canEdit: isLatest,
        canRegenerate: false,
        canBranch: true,
        canRewind: true,
        canPin: true,
        canRate: false,
        feedbackRating: checkpoint.feedback_rating,
      };
    }

    controlsByMessageId[assistantMessage.id] = {
      checkpointId: checkpoint.id,
      branchId: checkpoint.branch_id,
      canEdit: false,
      canRegenerate: isLatest,
      canBranch: false,
      canRewind: false,
      canPin: true,
      canRate: true,
      feedbackRating: checkpoint.feedback_rating,
    };

    canonicalStoredMessages.push(userMessage, assistantMessage);
  });

  const [rawTimeline, rawPins] = await Promise.all([
    listTimeline(supabase, threadId, activeBranch.id, 24),
    listPins(supabase, threadId, activeBranch.id),
  ]);
  const reachableCheckpointIds = new Set(checkpointPath.map((checkpoint) => checkpoint.id));
  const reachableMessageIds = new Set(canonicalStoredMessages.map((message) => message.id));
  const timeline = rawTimeline
    .filter((event) => {
      if (event.checkpoint_id) return reachableCheckpointIds.has(event.checkpoint_id);
      if (event.source_message_id) return reachableMessageIds.has(event.source_message_id);
      return true;
    })
    .slice(0, 8);
  const pins = rawPins.filter(
    (pin) => !pin.source_message_id || reachableMessageIds.has(pin.source_message_id),
  );

  const {
    headSnapshot,
    resolvedSnapshot,
    headSnapshotPending,
    headSnapshotFailed,
    headSnapshotFailureMessage,
  } = resolveSnapshotState(
    checkpointPath,
    snapshotsByCheckpointId,
    latestReconcileJob,
  );

  return {
    thread,
    branches,
    activeBranch,
    checkpoints: checkpointPath,
    latestCheckpoint,
    headSnapshot,
    resolvedSnapshot,
    headSnapshotPending,
    headSnapshotFailed,
    headSnapshotFailureMessage,
    timeline,
    pins,
    canonicalMessages: toUIMessages(canonicalStoredMessages),
    modelContextMessages: toUIMessages(canonicalStoredMessages, { includeHidden: true }),
    controlsByMessageId,
  };
}

export function buildCheckpointPath(
  checkpoints: ChatCheckpointRecord[],
  headCheckpointId: string | null,
) {
  if (!headCheckpointId) return [];
  const checkpointsById = new Map(checkpoints.map((checkpoint) => [checkpoint.id, checkpoint]));
  const path: ChatCheckpointRecord[] = [];
  let pointer: string | null = headCheckpointId;

  while (pointer) {
    const checkpoint = checkpointsById.get(pointer);
    if (!checkpoint) break;
    path.push(checkpoint);
    pointer = checkpoint.parent_checkpoint_id;
  }

  return path.reverse();
}

export function createTextMessage(args: {
  id?: string;
  role: "user" | "assistant" | "system";
  text: string;
  metadata?: MessageMetadata;
}) {
  return {
    id: args.id ?? crypto.randomUUID(),
    role: args.role,
    parts: args.text
      ? [
          {
            type: "text" as const,
            text: args.text,
          },
        ]
      : [],
    metadata: args.metadata ?? {},
  } satisfies FantasiaUIMessage;
}

export function truncateMessageText(message: Pick<FantasiaUIMessage, "parts">, length = 120) {
  const text = getTextFromMessageParts(message.parts);
  if (text.length <= length) return text;
  return `${text.slice(0, length).trim()}...`;
}
