import { castRow, castRows, type DatabaseClient } from "@/lib/data/shared";
import type {
  ConnectionRecord,
  ThreadListItem,
  ThreadRecord,
} from "@/lib/types";

export const threadSelect = [
  "id",
  "user_id",
  "character_id",
  "connection_id",
  "model_id",
  "persona_id",
  "active_branch_id",
  "title",
  "is_title_autogenerated",
  "status",
  "archived_at",
  "pinned_at",
  "temperature_override",
  "top_p_override",
  "max_output_tokens_override",
  "created_at",
  "updated_at",
].join(", ");

const threadListSelect = `${threadSelect}, characters(name), user_personas(name)`;

function sortThreads<T extends ThreadRecord>(threads: T[]) {
  return [...threads].sort((left, right) => {
    const leftPinned = left.pinned_at ? new Date(left.pinned_at).getTime() : 0;
    const rightPinned = right.pinned_at ? new Date(right.pinned_at).getTime() : 0;
    if (leftPinned !== rightPinned) return rightPinned - leftPinned;
    return new Date(right.updated_at).getTime() - new Date(left.updated_at).getTime();
  });
}

function buildThreadListQuery(
  supabase: DatabaseClient,
  userId: string,
  status: "active" | "archived" | "all",
) {
  let queryBuilder = supabase
    .from("chat_threads")
    .select(threadListSelect)
    .eq("user_id", userId)
    .not("active_branch_id", "is", null);

  if (status !== "all") {
    queryBuilder = queryBuilder.eq("status", status);
  }

  return queryBuilder;
}

async function selectThreadItems(
  query: ReturnType<typeof buildThreadListQuery>,
) {
  const { data, error } = await query;

  if (error) throw error;
  return castRows<ThreadListItem>(data, "Thread list items");
}

export async function listThreads(supabase: DatabaseClient, userId: string) {
  return listThreadItems(supabase, userId, { status: "active" });
}

export async function listThreadItems(
  supabase: DatabaseClient,
  userId: string,
  options?: {
    query?: string;
    status?: "active" | "archived" | "all";
  },
) {
  const status = options?.status ?? "all";
  const query = options?.query?.trim() ?? "";

  if (!query) {
    return sortThreads(
      await selectThreadItems(buildThreadListQuery(supabase, userId, status)),
    );
  }

  const [titleMatches, characterIdRows, personaIdRows] = await Promise.all([
    selectThreadItems(
      buildThreadListQuery(supabase, userId, status).ilike("title", `%${query}%`),
    ),
    supabase
      .from("characters")
      .select("id")
      .eq("user_id", userId)
      .ilike("name", `%${query}%`),
    supabase
      .from("user_personas")
      .select("id")
      .eq("user_id", userId)
      .ilike("name", `%${query}%`),
  ]);

  if (characterIdRows.error) throw characterIdRows.error;
  if (personaIdRows.error) throw personaIdRows.error;

  const characterIds = castRows<{ id: string }>(characterIdRows.data ?? [], "Character ids").map(
    (row) => row.id,
  );
  const personaIds = castRows<{ id: string }>(personaIdRows.data ?? [], "Persona ids").map(
    (row) => row.id,
  );

  const relatedMatches = await Promise.all([
    characterIds.length
      ? selectThreadItems(
          buildThreadListQuery(supabase, userId, status).in("character_id", characterIds),
        )
      : Promise.resolve([] as ThreadListItem[]),
    personaIds.length
      ? selectThreadItems(
          buildThreadListQuery(supabase, userId, status).in("persona_id", personaIds),
        )
      : Promise.resolve([] as ThreadListItem[]),
  ]);

  const merged = new Map<string, ThreadListItem>();
  for (const thread of [titleMatches, ...relatedMatches].flat()) {
    merged.set(thread.id, thread);
  }

  return sortThreads(Array.from(merged.values()));
}

export async function getThread(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .select(threadSelect)
    .eq("user_id", userId)
    .eq("id", threadId)
    .maybeSingle();

  if (error) throw error;
  return data ? castRow<ThreadRecord>(data) : null;
}

export async function createThread(
  supabase: DatabaseClient,
  userId: string,
  args: {
    characterId: string;
    connection: ConnectionRecord;
    modelId: string;
    title: string;
    personaId: string;
  },
) {
  const { data, error } = await supabase.rpc("create_thread_with_main_branch", {
    p_user_id: userId,
    p_character_id: args.characterId,
    p_connection_id: args.connection.id,
    p_model_id: args.modelId,
    p_persona_id: args.personaId,
    p_title: args.title,
  });

  if (error) throw error;
  return castRow<ThreadRecord>(data, "Created thread");
}

export async function updateThreadModel(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; connectionId: string; modelId: string },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({
      connection_id: args.connectionId,
      model_id: args.modelId,
    })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) throw error;
  return castRow<ThreadRecord>(data);
}

export async function updateThreadPersona(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; personaId: string },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({ persona_id: args.personaId })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) throw error;
  return castRow<ThreadRecord>(data);
}

export async function switchActiveBranch(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; branchId: string },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({ active_branch_id: args.branchId })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) throw error;
  return castRow<ThreadRecord>(data);
}

export async function renameThread(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
  title: string,
) {
  const { error } = await supabase
    .from("chat_threads")
    .update({
      title,
      is_title_autogenerated: false,
      updated_at: new Date().toISOString(),
    })
    .eq("id", threadId)
    .eq("user_id", userId);

  if (error) throw error;
  return getThread(supabase, userId, threadId);
}

export async function updateThreadPinnedState(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; pinned: boolean },
) {
  const { data, error } = await supabase
    .from("chat_threads")
    .update({
      pinned_at: args.pinned ? new Date().toISOString() : null,
      updated_at: new Date().toISOString(),
    })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) throw error;
  return castRow<ThreadRecord>(data);
}

export async function updateThreadStatus(
  supabase: DatabaseClient,
  userId: string,
  args: { threadId: string; status: ThreadRecord["status"] },
) {
  const archivedAt = args.status === "archived" ? new Date().toISOString() : null;
  const { data, error } = await supabase
    .from("chat_threads")
    .update({
      status: args.status,
      archived_at: archivedAt,
      updated_at: new Date().toISOString(),
    })
    .eq("id", args.threadId)
    .eq("user_id", userId)
    .select(threadSelect)
    .single();

  if (error) throw error;
  return castRow<ThreadRecord>(data);
}

export async function deleteThread(
  supabase: DatabaseClient,
  userId: string,
  threadId: string,
) {
  const { error } = await supabase
    .from("chat_threads")
    .delete()
    .eq("id", threadId)
    .eq("user_id", userId);

  if (error) throw error;
}
