create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  is_allowed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ai_connections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null check (provider in ('google', 'groq', 'mistral', 'openrouter', 'ollama')),
  label text not null,
  base_url text,
  encrypted_api_key text,
  enabled boolean not null default true,
  model_cache jsonb not null default '[]'::jsonb,
  health_status text not null default 'untested'
    check (health_status in ('untested', 'healthy', 'auth_failed', 'bad_config', 'bad_base_url', 'rate_limited', 'error')),
  health_message text not null default '',
  last_checked_at timestamptz,
  last_model_refresh_at timestamptz,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_personas (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  identity text not null default '',
  backstory text not null default '',
  voice_style text not null default '',
  goals text not null default '',
  boundaries text not null default '',
  private_notes text not null default '',
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.characters (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  story text not null default '',
  core_persona text not null default '',
  greeting text not null default '',
  appearance text not null default '',
  style_rules text not null default '',
  definition text not null default '',
  negative_guidance text not null default '',
  portrait_status text not null default 'idle'
    check (portrait_status in ('idle', 'pending', 'ready', 'failed')),
  portrait_path text not null default '',
  portrait_prompt text not null default '',
  portrait_seed integer,
  portrait_source_hash text not null default '',
  portrait_last_error text not null default '',
  portrait_generated_at timestamptz,
  temperature numeric(3,2) not null default 0.92 check (temperature >= 0 and temperature <= 2),
  top_p numeric(3,2) not null default 0.94 check (top_p > 0 and top_p <= 1),
  max_output_tokens integer not null default 750 check (max_output_tokens > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'character-portraits',
  'character-portraits',
  true,
  5242880,
  array['image/jpeg']
)
on conflict (id) do nothing;

create table public.character_starters (
  id uuid primary key default gen_random_uuid(),
  character_id uuid not null references public.characters(id) on delete cascade,
  text text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.character_example_conversations (
  id uuid primary key default gen_random_uuid(),
  character_id uuid not null references public.characters(id) on delete cascade,
  user_line text not null default '',
  character_line text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chat_threads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  character_id uuid not null references public.characters(id) on delete cascade,
  connection_id uuid not null references public.ai_connections(id) on delete restrict,
  model_id text not null,
  persona_id uuid references public.user_personas(id) on delete set null,
  active_branch_id uuid,
  title text not null default 'New roleplay thread',
  is_title_autogenerated boolean not null default true,
  status text not null default 'active' check (status in ('active', 'archived')),
  archived_at timestamptz,
  pinned_at timestamptz,
  temperature_override numeric(3,2) check (temperature_override is null or (temperature_override >= 0 and temperature_override <= 2)),
  top_p_override numeric(3,2) check (top_p_override is null or (top_p_override > 0 and top_p_override <= 1)),
  max_output_tokens_override integer check (max_output_tokens_override is null or max_output_tokens_override > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chat_messages (
  id text primary key,
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  parts jsonb not null default '[]'::jsonb,
  content_text text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.chat_branches (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  name text not null,
  parent_branch_id uuid references public.chat_branches(id) on delete set null,
  fork_checkpoint_id uuid,
  head_checkpoint_id uuid,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chat_checkpoints (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_id uuid not null references public.chat_branches(id) on delete cascade,
  parent_checkpoint_id uuid references public.chat_checkpoints(id) on delete set null,
  user_message_id text not null references public.chat_messages(id) on delete cascade,
  assistant_message_id text not null references public.chat_messages(id) on delete cascade,
  choice_group_key text not null,
  feedback_rating integer check (feedback_rating between 1 and 4),
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.chat_threads
  add constraint chat_threads_active_branch_id_fkey
  foreign key (active_branch_id)
  references public.chat_branches(id)
  on delete set null;

alter table public.chat_branches
  add constraint chat_branches_fork_checkpoint_id_fkey
  foreign key (fork_checkpoint_id)
  references public.chat_checkpoints(id)
  on delete set null;

alter table public.chat_branches
  add constraint chat_branches_head_checkpoint_id_fkey
  foreign key (head_checkpoint_id)
  references public.chat_checkpoints(id)
  on delete set null;

create table public.chat_state_snapshots (
  checkpoint_id uuid primary key references public.chat_checkpoints(id) on delete cascade,
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_id uuid not null references public.chat_branches(id) on delete cascade,
  based_on_snapshot_id uuid references public.chat_state_snapshots(checkpoint_id) on delete set null,
  scenario_state text not null default '',
  relationship_state text not null default '',
  rolling_summary text not null default '',
  user_facts jsonb not null default '[]'::jsonb,
  open_loops jsonb not null default '[]'::jsonb,
  resolved_loops jsonb not null default '[]'::jsonb,
  narrative_hooks jsonb not null default '[]'::jsonb,
  scene_goals jsonb not null default '[]'::jsonb,
  version integer not null default 1,
  updated_at timestamptz not null default now()
);

create table public.chat_timeline_events (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_id uuid references public.chat_branches(id) on delete cascade,
  checkpoint_id uuid references public.chat_checkpoints(id) on delete set null,
  source_message_id text references public.chat_messages(id) on delete set null,
  title text not null,
  detail text not null,
  importance integer not null default 3 check (importance between 1 and 5),
  created_at timestamptz not null default now()
);

create table public.chat_pins (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_id uuid not null references public.chat_branches(id) on delete cascade,
  source_message_id text references public.chat_messages(id) on delete set null,
  body text not null,
  status text not null default 'active' check (status in ('active', 'resolved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.background_jobs (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  status text not null default 'pending' check (status in ('pending', 'running', 'succeeded', 'failed')),
  user_id uuid not null references public.profiles(id) on delete cascade,
  thread_id uuid references public.chat_threads(id) on delete cascade,
  branch_id uuid references public.chat_branches(id) on delete cascade,
  checkpoint_id uuid references public.chat_checkpoints(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 5 check (max_attempts > 0),
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.claim_background_jobs(limit_count integer default 10)
returns setof public.background_jobs
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with selected as (
    select jobs.id
    from public.background_jobs jobs
    where jobs.status = 'pending'
      and jobs.available_at <= now()
      and (jobs.locked_at is null or jobs.locked_at < now() - interval '10 minutes')
    order by jobs.available_at asc, jobs.created_at asc
    limit limit_count
    for update skip locked
  ),
  updated as (
    update public.background_jobs jobs
    set
      status = 'running',
      attempts = jobs.attempts + 1,
      locked_at = now(),
      updated_at = now()
    where jobs.id in (select id from selected)
    returning jobs.*
  )
  select * from updated;
end;
$$;

revoke all on function public.claim_background_jobs(integer) from public;

create index idx_ai_connections_user_id on public.ai_connections(user_id);
create index idx_ai_connections_health on public.ai_connections(user_id, health_status, updated_at desc);
create index idx_user_personas_user_id on public.user_personas(user_id);
create unique index idx_user_personas_default_unique on public.user_personas(user_id) where is_default = true;
create index idx_characters_user_id on public.characters(user_id, updated_at desc);
create index idx_character_starters_character_id on public.character_starters(character_id, sort_order);
create index idx_character_examples_character_id on public.character_example_conversations(character_id, sort_order);
create index idx_chat_threads_user_id on public.chat_threads(user_id, updated_at desc);
create index idx_chat_threads_status on public.chat_threads(user_id, status, archived_at desc nulls last, updated_at desc);
create index idx_chat_threads_pinned on public.chat_threads(user_id, pinned_at desc nulls last, updated_at desc);
create index idx_chat_messages_thread_id on public.chat_messages(thread_id, created_at);
create index idx_chat_branches_thread_id on public.chat_branches(thread_id, updated_at desc);
create index idx_chat_checkpoints_branch_id on public.chat_checkpoints(branch_id, created_at);
create index idx_chat_checkpoints_choice_group on public.chat_checkpoints(choice_group_key, created_at);
create index idx_chat_state_snapshots_thread_id on public.chat_state_snapshots(thread_id, updated_at desc);
create index idx_chat_timeline_events_branch_id on public.chat_timeline_events(branch_id, created_at desc);
create index idx_chat_pins_branch_id on public.chat_pins(branch_id, created_at desc);
create index idx_background_jobs_pending on public.background_jobs(status, available_at, created_at);
create index idx_background_jobs_checkpoint on public.background_jobs(checkpoint_id);

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

create trigger set_ai_connections_updated_at
before update on public.ai_connections
for each row execute procedure public.set_updated_at();

create trigger set_user_personas_updated_at
before update on public.user_personas
for each row execute procedure public.set_updated_at();

create trigger set_characters_updated_at
before update on public.characters
for each row execute procedure public.set_updated_at();

create trigger set_character_starters_updated_at
before update on public.character_starters
for each row execute procedure public.set_updated_at();

create trigger set_character_example_conversations_updated_at
before update on public.character_example_conversations
for each row execute procedure public.set_updated_at();

create trigger set_chat_threads_updated_at
before update on public.chat_threads
for each row execute procedure public.set_updated_at();

create trigger set_chat_branches_updated_at
before update on public.chat_branches
for each row execute procedure public.set_updated_at();

create trigger set_chat_pins_updated_at
before update on public.chat_pins
for each row execute procedure public.set_updated_at();

create trigger set_background_jobs_updated_at
before update on public.background_jobs
for each row execute procedure public.set_updated_at();

grant usage on schema public to anon, authenticated, service_role;

grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
grant all on all routines in schema public to anon, authenticated, service_role;

alter default privileges in schema public
grant all on tables to anon, authenticated, service_role;

alter default privileges in schema public
grant all on sequences to anon, authenticated, service_role;

alter default privileges in schema public
grant all on routines to anon, authenticated, service_role;

alter table public.profiles enable row level security;
alter table public.ai_connections enable row level security;
alter table public.user_personas enable row level security;
alter table public.characters enable row level security;
alter table public.character_starters enable row level security;
alter table public.character_example_conversations enable row level security;
alter table public.chat_threads enable row level security;
alter table public.chat_messages enable row level security;
alter table public.chat_branches enable row level security;
alter table public.chat_checkpoints enable row level security;
alter table public.chat_state_snapshots enable row level security;
alter table public.chat_timeline_events enable row level security;
alter table public.chat_pins enable row level security;
alter table public.background_jobs enable row level security;

create policy "profiles own rows"
on public.profiles
for all
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "connections own rows"
on public.ai_connections
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "personas own rows"
on public.user_personas
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "characters own rows"
on public.characters
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "starters via owned characters"
on public.character_starters
for all
using (
  exists (
    select 1
    from public.characters characters
    where characters.id = character_starters.character_id
      and characters.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.characters characters
    where characters.id = character_starters.character_id
      and characters.user_id = auth.uid()
  )
);

create policy "examples via owned characters"
on public.character_example_conversations
for all
using (
  exists (
    select 1
    from public.characters characters
    where characters.id = character_example_conversations.character_id
      and characters.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.characters characters
    where characters.id = character_example_conversations.character_id
      and characters.user_id = auth.uid()
  )
);

create policy "threads own rows"
on public.chat_threads
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "messages via owned threads"
on public.chat_messages
for all
using (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_messages.thread_id
      and threads.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_messages.thread_id
      and threads.user_id = auth.uid()
  )
);

create policy "branches via owned threads"
on public.chat_branches
for all
using (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_branches.thread_id
      and threads.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_branches.thread_id
      and threads.user_id = auth.uid()
  )
);

create policy "checkpoints via owned threads"
on public.chat_checkpoints
for all
using (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_checkpoints.thread_id
      and threads.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_checkpoints.thread_id
      and threads.user_id = auth.uid()
  )
);

create policy "snapshots via owned threads"
on public.chat_state_snapshots
for all
using (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_state_snapshots.thread_id
      and threads.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_state_snapshots.thread_id
      and threads.user_id = auth.uid()
  )
);

create policy "timeline via owned threads"
on public.chat_timeline_events
for all
using (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_timeline_events.thread_id
      and threads.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_timeline_events.thread_id
      and threads.user_id = auth.uid()
  )
);

create policy "pins via owned threads"
on public.chat_pins
for all
using (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_pins.thread_id
      and threads.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_pins.thread_id
      and threads.user_id = auth.uid()
  )
);

create policy "jobs via owned user"
on public.background_jobs
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "character portrait objects are publicly readable"
on storage.objects
for select
using (bucket_id = 'character-portraits');
