create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  is_allowed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ai_connections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null check (provider in ('google', 'groq', 'mistral', 'openrouter', 'ollama')),
  label text not null,
  base_url text,
  encrypted_api_key text,
  enabled boolean not null default true,
  default_model_id text,
  model_cache jsonb not null default '[]'::jsonb check (jsonb_typeof(model_cache) = 'array'),
  health_status text not null default 'untested'
    check (
      health_status in (
        'untested',
        'healthy',
        'auth_failed',
        'rate_limited',
        'bad_base_url',
        'bad_config',
        'needs_attention',
        'error'
      )
    ),
  health_message text not null default '',
  last_checked_at timestamptz,
  last_model_refresh_at timestamptz,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_personas (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  identity text not null default '',
  backstory text not null default '',
  voice_style text not null default '',
  goals text not null default '',
  boundaries text not null default '',
  private_notes text not null default '',
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index user_personas_one_default_per_user
  on public.user_personas(user_id)
  where is_default = true;

create table public.characters (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  story text not null default '',
  core_persona text not null default '',
  greeting text not null default '',
  appearance text not null default '',
  style_rules text not null default '',
  definition text not null default '',
  negative_guidance text not null default '',
  starters jsonb not null default '[]'::jsonb check (jsonb_typeof(starters) = 'array'),
  example_conversations jsonb not null default '[]'::jsonb check (jsonb_typeof(example_conversations) = 'array'),
  portrait_status text not null default 'idle'
    check (portrait_status in ('idle', 'pending', 'ready', 'failed')),
  portrait_path text not null default '',
  portrait_prompt text not null default '',
  portrait_seed integer,
  portrait_source_hash text not null default '',
  portrait_last_error text not null default '',
  portrait_generated_at timestamptz,
  temperature numeric(3,2) not null default 0.92 check (temperature >= 0 and temperature <= 2),
  top_p numeric(3,2) not null default 0.94 check (top_p > 0 and top_p <= 1),
  max_output_tokens integer not null default 750 check (max_output_tokens > 0 and max_output_tokens <= 4096),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'character-portraits',
  'character-portraits',
  true,
  5242880,
  array['image/jpeg']
)
on conflict (id) do nothing;

create table public.chat_threads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  character_id uuid not null references public.characters(id) on delete cascade,
  connection_id uuid not null references public.ai_connections(id) on delete restrict,
  model_id text not null,
  persona_id uuid references public.user_personas(id) on delete set null,
  title text not null default 'New roleplay thread',
  is_title_autogenerated boolean not null default true,
  status text not null default 'active' check (status in ('active', 'archived')),
  archived_at timestamptz,
  pinned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chat_branches (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  name text not null,
  parent_branch_id uuid references public.chat_branches(id) on delete set null,
  fork_turn_id uuid,
  head_turn_id uuid,
  is_active boolean not null default false,
  generation_locked boolean not null default false,
  locked_by_turn_id uuid,
  locked_at timestamptz,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index chat_branches_one_active_per_thread
  on public.chat_branches(thread_id)
  where is_active = true;

create unique index chat_branches_id_thread_key
  on public.chat_branches(id, thread_id);

create table public.chat_turns (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_origin_id uuid not null,
  parent_turn_id uuid,
  user_input_text text not null default '',
  user_input_payload jsonb not null default '[]'::jsonb check (jsonb_typeof(user_input_payload) = 'array'),
  user_input_hidden boolean not null default false,
  starter_seed boolean not null default false,
  assistant_output_text text,
  assistant_output_payload jsonb check (
    assistant_output_payload is null or jsonb_typeof(assistant_output_payload) = 'array'
  ),
  generation_status text not null default 'reserved'
    check (generation_status in ('reserved', 'streaming', 'committed', 'failed')),
  reserved_by_user_id uuid not null references public.profiles(id) on delete cascade,
  assistant_provider text,
  assistant_model text,
  assistant_connection_label text,
  finish_reason text,
  total_tokens integer,
  prompt_tokens integer,
  completion_tokens integer,
  feedback_rating integer check (feedback_rating between 1 and 4),
  generation_started_at timestamptz not null default now(),
  generation_finished_at timestamptz,
  failure_code text,
  failure_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chat_turns_branch_origin_fkey
    foreign key (branch_origin_id, thread_id)
    references public.chat_branches(id, thread_id)
    on delete restrict
);

create unique index chat_turns_id_thread_key
  on public.chat_turns(id, thread_id);

alter table public.chat_turns
  add constraint chat_turns_parent_turn_fkey
  foreign key (parent_turn_id, thread_id)
  references public.chat_turns(id, thread_id)
  on delete restrict;

alter table public.chat_branches
  add constraint chat_branches_fork_turn_fkey
  foreign key (fork_turn_id, thread_id)
  references public.chat_turns(id, thread_id)
  on delete restrict;

alter table public.chat_branches
  add constraint chat_branches_head_turn_fkey
  foreign key (head_turn_id, thread_id)
  references public.chat_turns(id, thread_id)
  on delete restrict;

alter table public.chat_branches
  add constraint chat_branches_locked_turn_fkey
  foreign key (locked_by_turn_id, thread_id)
  references public.chat_turns(id, thread_id)
  on delete restrict;

create table public.chat_turn_snapshots (
  turn_id uuid primary key references public.chat_turns(id) on delete cascade,
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_id uuid not null references public.chat_branches(id) on delete cascade,
  based_on_turn_id uuid references public.chat_turns(id) on delete set null,
  scenario_state text not null default '',
  relationship_state text not null default '',
  rolling_summary text not null default '',
  user_facts jsonb not null default '[]'::jsonb check (jsonb_typeof(user_facts) = 'array'),
  open_loops jsonb not null default '[]'::jsonb check (jsonb_typeof(open_loops) = 'array'),
  resolved_loops jsonb not null default '[]'::jsonb check (jsonb_typeof(resolved_loops) = 'array'),
  narrative_hooks jsonb not null default '[]'::jsonb check (jsonb_typeof(narrative_hooks) = 'array'),
  scene_goals jsonb not null default '[]'::jsonb check (jsonb_typeof(scene_goals) = 'array'),
  version integer not null default 1 check (version > 0),
  updated_at timestamptz not null default now()
);

create table public.chat_timeline_events (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_id uuid not null references public.chat_branches(id) on delete cascade,
  turn_id uuid references public.chat_turns(id) on delete set null,
  title text not null,
  detail text not null,
  importance integer not null default 3 check (importance between 1 and 5),
  created_at timestamptz not null default now()
);

create table public.chat_pins (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_id uuid not null references public.chat_branches(id) on delete cascade,
  turn_id uuid references public.chat_turns(id) on delete set null,
  body text not null,
  status text not null default 'active' check (status in ('active', 'resolved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.turn_reconcile_tasks (
  id uuid primary key default gen_random_uuid(),
  turn_id uuid not null unique references public.chat_turns(id) on delete cascade,
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_id uuid not null references public.chat_branches(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  connection_id uuid not null references public.ai_connections(id) on delete restrict,
  model_id text not null,
  character_id uuid not null references public.characters(id) on delete cascade,
  persona_id uuid not null references public.user_personas(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 8 check (max_attempts > 0),
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.character_portrait_tasks (
  id uuid primary key default gen_random_uuid(),
  character_id uuid not null references public.characters(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  prompt text not null,
  seed integer not null,
  source_hash text not null,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 8 check (max_attempts > 0),
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index ai_connections_user_updated_idx
  on public.ai_connections(user_id, updated_at desc);

create index user_personas_user_updated_idx
  on public.user_personas(user_id, updated_at desc);

create index characters_user_updated_idx
  on public.characters(user_id, updated_at desc);

create index chat_threads_user_status_updated_idx
  on public.chat_threads(user_id, status, pinned_at desc nulls last, updated_at desc);

create index chat_branches_thread_updated_idx
  on public.chat_branches(thread_id, updated_at desc);

create index chat_turns_thread_created_idx
  on public.chat_turns(thread_id, created_at desc);

create index chat_turns_parent_turn_idx
  on public.chat_turns(parent_turn_id);

create index chat_turn_snapshots_branch_updated_idx
  on public.chat_turn_snapshots(branch_id, updated_at desc);

create index chat_timeline_events_branch_created_idx
  on public.chat_timeline_events(branch_id, created_at desc);

create index chat_pins_branch_created_idx
  on public.chat_pins(branch_id, status, created_at desc);

create index turn_reconcile_tasks_claim_idx
  on public.turn_reconcile_tasks(status, available_at, created_at);

create index character_portrait_tasks_claim_idx
  on public.character_portrait_tasks(status, available_at, created_at);

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger set_ai_connections_updated_at
before update on public.ai_connections
for each row execute function public.set_updated_at();

create trigger set_user_personas_updated_at
before update on public.user_personas
for each row execute function public.set_updated_at();

create trigger set_characters_updated_at
before update on public.characters
for each row execute function public.set_updated_at();

create trigger set_chat_threads_updated_at
before update on public.chat_threads
for each row execute function public.set_updated_at();

create trigger set_chat_branches_updated_at
before update on public.chat_branches
for each row execute function public.set_updated_at();

create trigger set_chat_turns_updated_at
before update on public.chat_turns
for each row execute function public.set_updated_at();

create trigger set_chat_pins_updated_at
before update on public.chat_pins
for each row execute function public.set_updated_at();

create trigger set_turn_reconcile_tasks_updated_at
before update on public.turn_reconcile_tasks
for each row execute function public.set_updated_at();

create trigger set_character_portrait_tasks_updated_at
before update on public.character_portrait_tasks
for each row execute function public.set_updated_at();

create or replace function public.owns_thread(target_thread_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.chat_threads
    where id = target_thread_id
      and user_id = auth.uid()
  );
$$;

create or replace function public.set_default_persona(target_persona_id uuid)
returns public.user_personas
language plpgsql
security invoker
set search_path = public
as $$
declare
  selected_persona public.user_personas;
begin
  select *
  into selected_persona
  from public.user_personas
  where id = target_persona_id
    and user_id = auth.uid();

  if not found then
    raise exception 'Persona not found or not owned by current user.'
      using errcode = 'P0001';
  end if;

  update public.user_personas
  set is_default = (id = target_persona_id),
      updated_at = now()
  where user_id = auth.uid();

  select *
  into selected_persona
  from public.user_personas
  where id = target_persona_id;

  return selected_persona;
end;
$$;

create or replace function public.activate_branch(
  p_thread_id uuid,
  p_branch_id uuid
)
returns public.chat_branches
language plpgsql
security invoker
set search_path = public
as $$
declare
  target_branch public.chat_branches;
begin
  if not public.owns_thread(p_thread_id) then
    raise exception 'Thread not found or not owned by current user.'
      using errcode = 'P0001';
  end if;

  select *
  into target_branch
  from public.chat_branches
  where id = p_branch_id
    and thread_id = p_thread_id;

  if not found then
    raise exception 'Branch not found on the target thread.'
      using errcode = 'P0001';
  end if;

  update public.chat_branches
  set is_active = false,
      updated_at = now()
  where thread_id = p_thread_id
    and is_active = true;

  update public.chat_branches
  set is_active = true,
      updated_at = now()
  where id = p_branch_id
    and thread_id = p_thread_id
  returning *
  into target_branch;

  return target_branch;
end;
$$;

create or replace function public.begin_turn(
  p_branch_id uuid,
  p_expected_head_turn_id uuid,
  p_user_input_text text,
  p_user_input_payload jsonb default '[]'::jsonb,
  p_parent_turn_id_override uuid default null,
  p_force_parent_override boolean default false,
  p_user_input_hidden boolean default false,
  p_starter_seed boolean default false
)
returns public.chat_turns
language plpgsql
security invoker
set search_path = public
as $$
declare
  target_branch public.chat_branches;
  target_thread public.chat_threads;
  reserved_turn public.chat_turns;
begin
  select *
  into target_branch
  from public.chat_branches
  where id = p_branch_id;

  if not found then
    raise exception 'Branch not found or not owned by current user.'
      using errcode = 'P0001';
  end if;

  select *
  into target_thread
  from public.chat_threads
  where id = target_branch.thread_id
    and user_id = auth.uid();

  if not found then
    raise exception 'Branch not found or not owned by current user.'
      using errcode = 'P0001';
  end if;

  if target_branch.generation_locked then
    raise exception 'A turn is already generating on this branch.'
      using errcode = 'P0001';
  end if;

  if target_branch.head_turn_id is distinct from p_expected_head_turn_id then
    raise exception 'Branch head changed before generation could begin.'
      using errcode = 'P0001';
  end if;

  insert into public.chat_turns (
    thread_id,
    branch_origin_id,
    parent_turn_id,
    user_input_text,
    user_input_payload,
    user_input_hidden,
    starter_seed,
    generation_status,
    reserved_by_user_id
  ) values (
    target_branch.thread_id,
    target_branch.id,
    case
      when coalesce(p_force_parent_override, false) then p_parent_turn_id_override
      else target_branch.head_turn_id
    end,
    coalesce(p_user_input_text, ''),
    coalesce(p_user_input_payload, '[]'::jsonb),
    coalesce(p_user_input_hidden, false),
    coalesce(p_starter_seed, false),
    'reserved',
    auth.uid()
  )
  returning *
  into reserved_turn;

  update public.chat_branches
  set generation_locked = true,
      locked_by_turn_id = reserved_turn.id,
      locked_at = now(),
      updated_at = now()
  where id = target_branch.id;

  return reserved_turn;
end;
$$;

create or replace function public.commit_turn(
  p_branch_id uuid,
  p_turn_id uuid,
  p_assistant_output_text text,
  p_assistant_output_payload jsonb,
  p_assistant_provider text,
  p_assistant_model text,
  p_assistant_connection_label text,
  p_finish_reason text,
  p_total_tokens integer,
  p_prompt_tokens integer,
  p_completion_tokens integer
)
returns public.chat_turns
language plpgsql
security invoker
set search_path = public
as $$
declare
  target_branch public.chat_branches;
  committed_turn public.chat_turns;
  target_thread public.chat_threads;
begin
  select *
  into target_branch
  from public.chat_branches
  where id = p_branch_id;

  if not found then
    raise exception 'Branch not found or not owned by current user.'
      using errcode = 'P0001';
  end if;

  select *
  into target_thread
  from public.chat_threads
  where id = target_branch.thread_id
    and user_id = auth.uid();

  if not found then
    raise exception 'Branch not found or not owned by current user.'
      using errcode = 'P0001';
  end if;

  if target_branch.locked_by_turn_id is distinct from p_turn_id then
    raise exception 'This branch is not locked by the target turn.'
      using errcode = 'P0001';
  end if;

  update public.chat_turns
  set assistant_output_text = coalesce(p_assistant_output_text, ''),
      assistant_output_payload = coalesce(p_assistant_output_payload, '[]'::jsonb),
      assistant_provider = p_assistant_provider,
      assistant_model = p_assistant_model,
      assistant_connection_label = p_assistant_connection_label,
      finish_reason = p_finish_reason,
      total_tokens = p_total_tokens,
      prompt_tokens = p_prompt_tokens,
      completion_tokens = p_completion_tokens,
      generation_status = 'committed',
      generation_finished_at = now(),
      updated_at = now()
  where id = p_turn_id
    and thread_id = target_branch.thread_id
  returning *
  into committed_turn;

  if not found then
    raise exception 'Turn not found on the target branch.'
      using errcode = 'P0001';
  end if;

  update public.chat_branches
  set head_turn_id = p_turn_id,
      generation_locked = false,
      locked_by_turn_id = null,
      locked_at = null,
      updated_at = now()
  where id = p_branch_id;

  update public.chat_threads
  set updated_at = now()
  where id = target_branch.thread_id;

  if target_thread.persona_id is not null then
    insert into public.turn_reconcile_tasks (
      turn_id,
      thread_id,
      branch_id,
      user_id,
      connection_id,
      model_id,
      character_id,
      persona_id,
      status,
      attempts,
      available_at,
      locked_at,
      last_error
    ) values (
      committed_turn.id,
      committed_turn.thread_id,
      p_branch_id,
      target_thread.user_id,
      target_thread.connection_id,
      target_thread.model_id,
      target_thread.character_id,
      target_thread.persona_id,
      'pending',
      0,
      now(),
      null,
      null
    )
    on conflict (turn_id) do update
      set status = 'pending',
          attempts = 0,
          available_at = now(),
          locked_at = null,
          last_error = null,
          updated_at = now();
  end if;

  return committed_turn;
end;
$$;

create or replace function public.fail_turn(
  p_branch_id uuid,
  p_turn_id uuid,
  p_failure_code text,
  p_failure_message text
)
returns public.chat_turns
language plpgsql
security invoker
set search_path = public
as $$
declare
  target_branch public.chat_branches;
  failed_turn public.chat_turns;
begin
  select branches.*
  into target_branch
  from public.chat_branches branches
  join public.chat_threads threads on threads.id = branches.thread_id
  where branches.id = p_branch_id
    and threads.user_id = auth.uid();

  if not found then
    raise exception 'Branch not found or not owned by current user.'
      using errcode = 'P0001';
  end if;

  update public.chat_turns
  set generation_status = 'failed',
      generation_finished_at = now(),
      failure_code = p_failure_code,
      failure_message = p_failure_message,
      updated_at = now()
  where id = p_turn_id
    and thread_id = target_branch.thread_id
  returning *
  into failed_turn;

  if target_branch.locked_by_turn_id = p_turn_id then
    update public.chat_branches
    set generation_locked = false,
        locked_by_turn_id = null,
        locked_at = null,
        updated_at = now()
    where id = p_branch_id;
  end if;

  return failed_turn;
end;
$$;

create or replace function public.create_branch_from_turn(
  p_source_branch_id uuid,
  p_source_turn_id uuid,
  p_name text,
  p_make_active boolean default true
)
returns public.chat_branches
language plpgsql
security invoker
set search_path = public
as $$
declare
  source_branch public.chat_branches;
  source_turn public.chat_turns;
  created_branch public.chat_branches;
begin
  select branches.*
  into source_branch
  from public.chat_branches branches
  join public.chat_threads threads on threads.id = branches.thread_id
  where branches.id = p_source_branch_id
    and threads.user_id = auth.uid();

  if not found then
    raise exception 'Source branch not found or not owned by current user.'
      using errcode = 'P0001';
  end if;

  select *
  into source_turn
  from public.chat_turns
  where id = p_source_turn_id
    and thread_id = source_branch.thread_id;

  if not found then
    raise exception 'Source turn not found on the selected thread.'
      using errcode = 'P0001';
  end if;

  if p_make_active then
    update public.chat_branches
    set is_active = false,
        updated_at = now()
    where thread_id = source_branch.thread_id
      and is_active = true;
  end if;

  insert into public.chat_branches (
    thread_id,
    name,
    parent_branch_id,
    fork_turn_id,
    head_turn_id,
    is_active,
    created_by
  ) values (
    source_branch.thread_id,
    p_name,
    source_branch.id,
    source_turn.id,
    source_turn.id,
    p_make_active,
    auth.uid()
  )
  returning *
  into created_branch;

  update public.chat_threads
  set updated_at = now()
  where id = source_branch.thread_id;

  return created_branch;
end;
$$;

create or replace function public.rewind_branch_to_turn(
  p_branch_id uuid,
  p_target_turn_id uuid,
  p_expected_head_turn_id uuid default null
)
returns public.chat_branches
language plpgsql
security invoker
set search_path = public
as $$
declare
  target_branch public.chat_branches;
  resolved_branch public.chat_branches;
  target_is_reachable boolean;
begin
  select branches.*
  into target_branch
  from public.chat_branches branches
  join public.chat_threads threads on threads.id = branches.thread_id
  where branches.id = p_branch_id
    and threads.user_id = auth.uid();

  if not found then
    raise exception 'Branch not found or not owned by current user.'
      using errcode = 'P0001';
  end if;

  if target_branch.generation_locked then
    raise exception 'Cannot rewind while this branch is locked for generation.'
      using errcode = 'P0001';
  end if;

  if p_expected_head_turn_id is not null
     and target_branch.head_turn_id is distinct from p_expected_head_turn_id then
    raise exception 'Branch head changed before rewind could complete.'
      using errcode = 'P0001';
  end if;

  with recursive reachable as (
    select id, parent_turn_id, 1 as depth
    from public.chat_turns
    where id = target_branch.head_turn_id
      and thread_id = target_branch.thread_id
    union all
    select parent.id, parent.parent_turn_id, reachable.depth + 1
    from public.chat_turns parent
    join reachable on reachable.parent_turn_id = parent.id
    where parent.thread_id = target_branch.thread_id
      and reachable.depth < 5000
  )
  select exists (
    select 1
    from reachable
    where id = p_target_turn_id
  )
  into target_is_reachable;

  if not target_is_reachable then
    raise exception 'Target turn is not reachable from the current branch head.'
      using errcode = 'P0001';
  end if;

  update public.chat_branches
  set head_turn_id = p_target_turn_id,
      updated_at = now()
  where id = p_branch_id
  returning *
  into resolved_branch;

  update public.chat_threads
  set updated_at = now()
  where id = target_branch.thread_id;

  return resolved_branch;
end;
$$;

create or replace function public.claim_turn_reconcile_tasks(limit_count integer default 5)
returns setof public.turn_reconcile_tasks
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with selected as (
    select tasks.id
    from public.turn_reconcile_tasks tasks
    where tasks.status = 'pending'
      and tasks.available_at <= now()
      and (tasks.locked_at is null or tasks.locked_at < now() - interval '10 minutes')
    order by tasks.available_at asc, tasks.created_at asc
    limit limit_count
    for update skip locked
  ),
  updated as (
    update public.turn_reconcile_tasks tasks
    set status = 'running',
        attempts = tasks.attempts + 1,
        locked_at = now(),
        updated_at = now()
    where tasks.id in (select id from selected)
    returning tasks.*
  )
  select * from updated;
end;
$$;

create or replace function public.claim_character_portrait_tasks(limit_count integer default 2)
returns setof public.character_portrait_tasks
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with selected as (
    select tasks.id
    from public.character_portrait_tasks tasks
    where tasks.status = 'pending'
      and tasks.available_at <= now()
      and (tasks.locked_at is null or tasks.locked_at < now() - interval '10 minutes')
    order by tasks.available_at asc, tasks.created_at asc
    limit limit_count
    for update skip locked
  ),
  updated as (
    update public.character_portrait_tasks tasks
    set status = 'running',
        attempts = tasks.attempts + 1,
        locked_at = now(),
        updated_at = now()
    where tasks.id in (select id from selected)
    returning tasks.*
  )
  select * from updated;
end;
$$;

create or replace function public.cleanup_stale_generation_locks(
  p_stale_before interval default interval '5 minutes'
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  cleaned_count integer := 0;
begin
  with stale as (
    select id, thread_id, locked_by_turn_id
    from public.chat_branches
    where generation_locked = true
      and locked_at is not null
      and locked_at < now() - p_stale_before
      and locked_by_turn_id is not null
  ),
  failed_turns as (
    update public.chat_turns turns
    set generation_status = 'failed',
        generation_finished_at = now(),
        failure_code = coalesce(turns.failure_code, 'timeout'),
        failure_message = coalesce(turns.failure_message, 'Generation lock expired before completion.'),
        updated_at = now()
    where turns.id in (select locked_by_turn_id from stale)
      and turns.generation_status in ('reserved', 'streaming')
    returning turns.id
  )
  update public.chat_branches branches
  set generation_locked = false,
      locked_by_turn_id = null,
      locked_at = null,
      updated_at = now()
  where branches.id in (select id from stale);

  get diagnostics cleaned_count = row_count;
  return cleaned_count;
end;
$$;

alter table public.profiles enable row level security;
alter table public.ai_connections enable row level security;
alter table public.user_personas enable row level security;
alter table public.characters enable row level security;
alter table public.chat_threads enable row level security;
alter table public.chat_branches enable row level security;
alter table public.chat_turns enable row level security;
alter table public.chat_turn_snapshots enable row level security;
alter table public.chat_timeline_events enable row level security;
alter table public.chat_pins enable row level security;
alter table public.turn_reconcile_tasks enable row level security;
alter table public.character_portrait_tasks enable row level security;

create policy "profiles_select_own"
on public.profiles
for select
using (auth.uid() = id);

create policy "profiles_insert_own"
on public.profiles
for insert
with check (auth.uid() = id);

create policy "profiles_update_own"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "connections_own"
on public.ai_connections
for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "personas_own"
on public.user_personas
for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "characters_own"
on public.characters
for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "threads_own"
on public.chat_threads
for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "branches_own_thread"
on public.chat_branches
for all
using (public.owns_thread(thread_id))
with check (public.owns_thread(thread_id));

create policy "turns_own_thread"
on public.chat_turns
for all
using (public.owns_thread(thread_id))
with check (public.owns_thread(thread_id));

create policy "snapshots_own_thread"
on public.chat_turn_snapshots
for all
using (public.owns_thread(thread_id))
with check (public.owns_thread(thread_id));

create policy "timeline_own_thread"
on public.chat_timeline_events
for all
using (public.owns_thread(thread_id))
with check (public.owns_thread(thread_id));

create policy "pins_own_thread"
on public.chat_pins
for all
using (public.owns_thread(thread_id))
with check (public.owns_thread(thread_id));

create policy "reconcile_tasks_own_thread"
on public.turn_reconcile_tasks
for select
using (public.owns_thread(thread_id));

create policy "portrait_tasks_own_user"
on public.character_portrait_tasks
for select
using (user_id = auth.uid());
