create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  is_allowed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ai_connections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null check (provider in ('google', 'groq', 'mistral', 'openrouter', 'ollama')),
  label text not null,
  base_url text,
  encrypted_api_key text,
  enabled boolean not null default true,
  model_cache jsonb not null default '[]'::jsonb,
  health_status text not null default 'untested'
    check (health_status in ('untested', 'healthy', 'auth_failed', 'bad_config', 'bad_base_url', 'rate_limited', 'error')),
  health_message text not null default '',
  last_checked_at timestamptz,
  last_model_refresh_at timestamptz,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_personas (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  identity text not null default '',
  backstory text not null default '',
  voice_style text not null default '',
  goals text not null default '',
  boundaries text not null default '',
  private_notes text not null default '',
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.characters (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  story text not null default '',
  core_persona text not null default '',
  greeting text not null default '',
  appearance text not null default '',
  style_rules text not null default '',
  definition text not null default '',
  negative_guidance text not null default '',
  portrait_status text not null default 'idle'
    check (portrait_status in ('idle', 'pending', 'ready', 'failed')),
  portrait_path text not null default '',
  portrait_prompt text not null default '',
  portrait_seed integer,
  portrait_source_hash text not null default '',
  portrait_last_error text not null default '',
  portrait_generated_at timestamptz,
  temperature numeric(3,2) not null default 0.92 check (temperature >= 0 and temperature <= 2),
  top_p numeric(3,2) not null default 0.94 check (top_p > 0 and top_p <= 1),
  max_output_tokens integer not null default 750 check (max_output_tokens > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'character-portraits',
  'character-portraits',
  true,
  5242880,
  array['image/jpeg']
)
on conflict (id) do nothing;

create table public.character_starters (
  id uuid primary key default gen_random_uuid(),
  character_id uuid not null references public.characters(id) on delete cascade,
  text text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.character_example_conversations (
  id uuid primary key default gen_random_uuid(),
  character_id uuid not null references public.characters(id) on delete cascade,
  user_line text not null default '',
  character_line text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chat_threads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  character_id uuid not null references public.characters(id) on delete cascade,
  connection_id uuid not null references public.ai_connections(id) on delete restrict,
  model_id text not null,
  persona_id uuid references public.user_personas(id) on delete set null,
  active_branch_id uuid,
  title text not null default 'New roleplay thread',
  is_title_autogenerated boolean not null default true,
  status text not null default 'active' check (status in ('active', 'archived')),
  archived_at timestamptz,
  pinned_at timestamptz,
  temperature_override numeric(3,2) check (temperature_override is null or (temperature_override >= 0 and temperature_override <= 2)),
  top_p_override numeric(3,2) check (top_p_override is null or (top_p_override > 0 and top_p_override <= 1)),
  max_output_tokens_override integer check (max_output_tokens_override is null or max_output_tokens_override > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chat_messages (
  id text primary key,
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  parts jsonb not null default '[]'::jsonb,
  content_text text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.chat_branches (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  name text not null,
  parent_branch_id uuid references public.chat_branches(id) on delete set null,
  fork_checkpoint_id uuid,
  head_checkpoint_id uuid,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chat_checkpoints (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_id uuid not null references public.chat_branches(id) on delete cascade,
  parent_checkpoint_id uuid references public.chat_checkpoints(id) on delete set null,
  user_message_id text not null references public.chat_messages(id) on delete cascade,
  assistant_message_id text not null references public.chat_messages(id) on delete cascade,
  choice_group_key text not null,
  feedback_rating integer check (feedback_rating between 1 and 4),
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.chat_threads
  add constraint chat_threads_active_branch_id_fkey
  foreign key (active_branch_id)
  references public.chat_branches(id)
  on delete set null;

alter table public.chat_branches
  add constraint chat_branches_fork_checkpoint_id_fkey
  foreign key (fork_checkpoint_id)
  references public.chat_checkpoints(id)
  on delete set null;

alter table public.chat_branches
  add constraint chat_branches_head_checkpoint_id_fkey
  foreign key (head_checkpoint_id)
  references public.chat_checkpoints(id)
  on delete set null;

create table public.chat_state_snapshots (
  checkpoint_id uuid primary key references public.chat_checkpoints(id) on delete cascade,
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_id uuid not null references public.chat_branches(id) on delete cascade,
  based_on_snapshot_id uuid references public.chat_state_snapshots(checkpoint_id) on delete set null,
  scenario_state text not null default '',
  relationship_state text not null default '',
  rolling_summary text not null default '',
  user_facts jsonb not null default '[]'::jsonb,
  open_loops jsonb not null default '[]'::jsonb,
  resolved_loops jsonb not null default '[]'::jsonb,
  narrative_hooks jsonb not null default '[]'::jsonb,
  scene_goals jsonb not null default '[]'::jsonb,
  version integer not null default 1,
  updated_at timestamptz not null default now()
);

create table public.chat_timeline_events (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_id uuid references public.chat_branches(id) on delete cascade,
  checkpoint_id uuid references public.chat_checkpoints(id) on delete set null,
  source_message_id text references public.chat_messages(id) on delete set null,
  title text not null,
  detail text not null,
  importance integer not null default 3 check (importance between 1 and 5),
  created_at timestamptz not null default now()
);

create table public.chat_pins (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  branch_id uuid not null references public.chat_branches(id) on delete cascade,
  source_message_id text references public.chat_messages(id) on delete set null,
  body text not null,
  status text not null default 'active' check (status in ('active', 'resolved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.background_jobs (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  status text not null default 'pending' check (status in ('pending', 'running', 'succeeded', 'failed')),
  user_id uuid not null references public.profiles(id) on delete cascade,
  thread_id uuid references public.chat_threads(id) on delete cascade,
  branch_id uuid references public.chat_branches(id) on delete cascade,
  checkpoint_id uuid references public.chat_checkpoints(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 5 check (max_attempts > 0),
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.claim_background_jobs(limit_count integer default 10)
returns setof public.background_jobs
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with selected as (
    select jobs.id
    from public.background_jobs jobs
    where jobs.status = 'pending'
      and jobs.available_at <= now()
      and (jobs.locked_at is null or jobs.locked_at < now() - interval '10 minutes')
    order by jobs.available_at asc, jobs.created_at asc
    limit limit_count
    for update skip locked
  ),
  updated as (
    update public.background_jobs jobs
    set
      status = 'running',
      attempts = jobs.attempts + 1,
      locked_at = now(),
      updated_at = now()
    where jobs.id in (select id from selected)
    returning jobs.*
  )
  select * from updated;
end;
$$;

revoke all on function public.claim_background_jobs(integer) from public;

create index idx_ai_connections_user_id on public.ai_connections(user_id);
create index idx_ai_connections_health on public.ai_connections(user_id, health_status, updated_at desc);
create index idx_user_personas_user_id on public.user_personas(user_id);
create unique index idx_user_personas_default_unique on public.user_personas(user_id) where is_default = true;
create index idx_characters_user_id on public.characters(user_id, updated_at desc);
create index idx_character_starters_character_id on public.character_starters(character_id, sort_order);
create index idx_character_examples_character_id on public.character_example_conversations(character_id, sort_order);
create index idx_chat_threads_user_id on public.chat_threads(user_id, updated_at desc);
create index idx_chat_threads_status on public.chat_threads(user_id, status, archived_at desc nulls last, updated_at desc);
create index idx_chat_threads_pinned on public.chat_threads(user_id, pinned_at desc nulls last, updated_at desc);
create index idx_chat_messages_thread_id on public.chat_messages(thread_id, created_at);
create index idx_chat_branches_thread_id on public.chat_branches(thread_id, updated_at desc);
create index idx_chat_checkpoints_branch_id on public.chat_checkpoints(branch_id, created_at);
create index idx_chat_checkpoints_choice_group on public.chat_checkpoints(choice_group_key, created_at);
create index idx_chat_state_snapshots_thread_id on public.chat_state_snapshots(thread_id, updated_at desc);
create index idx_chat_timeline_events_branch_id on public.chat_timeline_events(branch_id, created_at desc);
create index idx_chat_pins_branch_id on public.chat_pins(branch_id, created_at desc);
create index idx_background_jobs_pending on public.background_jobs(status, available_at, created_at);
create index idx_background_jobs_checkpoint on public.background_jobs(checkpoint_id);

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

create trigger set_ai_connections_updated_at
before update on public.ai_connections
for each row execute procedure public.set_updated_at();

create trigger set_user_personas_updated_at
before update on public.user_personas
for each row execute procedure public.set_updated_at();

create trigger set_characters_updated_at
before update on public.characters
for each row execute procedure public.set_updated_at();

create trigger set_character_starters_updated_at
before update on public.character_starters
for each row execute procedure public.set_updated_at();

create trigger set_character_example_conversations_updated_at
before update on public.character_example_conversations
for each row execute procedure public.set_updated_at();

create trigger set_chat_threads_updated_at
before update on public.chat_threads
for each row execute procedure public.set_updated_at();

create trigger set_chat_branches_updated_at
before update on public.chat_branches
for each row execute procedure public.set_updated_at();

create trigger set_chat_pins_updated_at
before update on public.chat_pins
for each row execute procedure public.set_updated_at();

create trigger set_background_jobs_updated_at
before update on public.background_jobs
for each row execute procedure public.set_updated_at();

grant usage on schema public to anon, authenticated, service_role;

grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
grant all on all routines in schema public to anon, authenticated, service_role;
revoke all on function public.claim_background_jobs(integer) from public;
revoke all on function public.claim_background_jobs(integer) from anon, authenticated;
grant execute on function public.claim_background_jobs(integer) to service_role;

alter default privileges in schema public
grant all on tables to anon, authenticated, service_role;

alter default privileges in schema public
grant all on sequences to anon, authenticated, service_role;

alter default privileges in schema public
grant all on routines to anon, authenticated, service_role;

alter table public.profiles enable row level security;
alter table public.ai_connections enable row level security;
alter table public.user_personas enable row level security;
alter table public.characters enable row level security;
alter table public.character_starters enable row level security;
alter table public.character_example_conversations enable row level security;
alter table public.chat_threads enable row level security;
alter table public.chat_messages enable row level security;
alter table public.chat_branches enable row level security;
alter table public.chat_checkpoints enable row level security;
alter table public.chat_state_snapshots enable row level security;
alter table public.chat_timeline_events enable row level security;
alter table public.chat_pins enable row level security;
alter table public.background_jobs enable row level security;

create policy "profiles own rows"
on public.profiles
for all
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "connections own rows"
on public.ai_connections
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "personas own rows"
on public.user_personas
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "characters own rows"
on public.characters
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "starters via owned characters"
on public.character_starters
for all
using (
  exists (
    select 1
    from public.characters characters
    where characters.id = character_starters.character_id
      and characters.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.characters characters
    where characters.id = character_starters.character_id
      and characters.user_id = auth.uid()
  )
);

create policy "examples via owned characters"
on public.character_example_conversations
for all
using (
  exists (
    select 1
    from public.characters characters
    where characters.id = character_example_conversations.character_id
      and characters.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.characters characters
    where characters.id = character_example_conversations.character_id
      and characters.user_id = auth.uid()
  )
);

create policy "threads own rows"
on public.chat_threads
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "messages via owned threads"
on public.chat_messages
for all
using (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_messages.thread_id
      and threads.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_messages.thread_id
      and threads.user_id = auth.uid()
  )
);

create policy "branches via owned threads"
on public.chat_branches
for all
using (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_branches.thread_id
      and threads.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_branches.thread_id
      and threads.user_id = auth.uid()
  )
);

create policy "checkpoints via owned threads"
on public.chat_checkpoints
for all
using (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_checkpoints.thread_id
      and threads.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_checkpoints.thread_id
      and threads.user_id = auth.uid()
  )
);

create policy "snapshots via owned threads"
on public.chat_state_snapshots
for all
using (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_state_snapshots.thread_id
      and threads.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_state_snapshots.thread_id
      and threads.user_id = auth.uid()
  )
);

create policy "timeline via owned threads"
on public.chat_timeline_events
for all
using (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_timeline_events.thread_id
      and threads.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_timeline_events.thread_id
      and threads.user_id = auth.uid()
  )
);

create policy "pins via owned threads"
on public.chat_pins
for all
using (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_pins.thread_id
      and threads.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_threads threads
    where threads.id = chat_pins.thread_id
      and threads.user_id = auth.uid()
  )
);

create policy "jobs via owned user"
on public.background_jobs
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "character portrait objects are publicly readable"
on storage.objects
for select
using (bucket_id = 'character-portraits');


-- Consolidated current schema: architecture stabilization and thread graph payload

create or replace function public.set_default_persona(
  target_persona_id uuid,
  target_user_id uuid
)
returns setof public.user_personas
language plpgsql
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.user_personas personas
    where personas.id = target_persona_id
      and personas.user_id = target_user_id
  ) then
    raise exception 'Persona % not found for user %', target_persona_id, target_user_id;
  end if;

  update public.user_personas
  set
    is_default = (id = target_persona_id),
    updated_at = now()
  where user_id = target_user_id
    and (is_default = true or id = target_persona_id);

  return query
  select *
  from public.user_personas personas
  where personas.user_id = target_user_id
  order by personas.is_default desc, personas.updated_at desc;
end;
$$;

create or replace function public.list_persona_usage(
  p_user_id uuid
)
returns table (
  persona_id uuid,
  total_threads bigint,
  active_threads bigint
)
language sql
set search_path = public
as $$
  select
    threads.persona_id,
    count(*)::bigint as total_threads,
    count(*) filter (where threads.status = 'active')::bigint as active_threads
  from public.chat_threads threads
  where threads.user_id = p_user_id
    and threads.persona_id is not null
  group by threads.persona_id;
$$;

create or replace function public.search_thread_library(
  p_user_id uuid,
  p_status text default 'all',
  p_query text default null,
  p_limit integer default null
)
returns table (
  id uuid,
  user_id uuid,
  character_id uuid,
  connection_id uuid,
  model_id text,
  persona_id uuid,
  active_branch_id uuid,
  title text,
  is_title_autogenerated boolean,
  status text,
  archived_at timestamptz,
  pinned_at timestamptz,
  temperature_override numeric,
  top_p_override numeric,
  max_output_tokens_override integer,
  created_at timestamptz,
  updated_at timestamptz,
  character_name text,
  persona_name text
)
language plpgsql
set search_path = public
as $$
declare
  normalized_query text := nullif(trim(coalesce(p_query, '')), '');
  applied_limit integer := case
    when p_limit is null or p_limit < 1 then null
    else p_limit
  end;
begin
  if auth.uid() is distinct from p_user_id then
    raise exception 'User mismatch for thread search.';
  end if;

  if p_status not in ('active', 'archived', 'all') then
    raise exception 'Unsupported thread status filter: %', p_status;
  end if;

  return query
  select
    threads.id,
    threads.user_id,
    threads.character_id,
    threads.connection_id,
    threads.model_id,
    threads.persona_id,
    threads.active_branch_id,
    threads.title,
    threads.is_title_autogenerated,
    threads.status,
    threads.archived_at,
    threads.pinned_at,
    threads.temperature_override,
    threads.top_p_override,
    threads.max_output_tokens_override,
    threads.created_at,
    threads.updated_at,
    characters.name as character_name,
    personas.name as persona_name
  from public.chat_threads threads
  join public.characters characters
    on characters.id = threads.character_id
   and characters.user_id = p_user_id
  left join public.user_personas personas
    on personas.id = threads.persona_id
   and personas.user_id = p_user_id
  where threads.user_id = p_user_id
    and threads.active_branch_id is not null
    and (p_status = 'all' or threads.status = p_status)
    and (
      normalized_query is null
      or threads.title ilike '%' || normalized_query || '%'
      or characters.name ilike '%' || normalized_query || '%'
      or coalesce(personas.name, '') ilike '%' || normalized_query || '%'
    )
  order by threads.pinned_at desc nulls last, threads.updated_at desc
  limit applied_limit;
end;
$$;

create or replace function public.delete_persona_and_reassign(
  p_user_id uuid,
  p_persona_id uuid
)
returns uuid
language plpgsql
set search_path = public
as $$
declare
  target_persona public.user_personas;
  replacement_persona public.user_personas;
  used_in_threads bigint := 0;
begin
  select *
  into target_persona
  from public.user_personas personas
  where personas.id = p_persona_id
    and personas.user_id = p_user_id;

  if target_persona.id is null then
    return null;
  end if;

  select *
  into replacement_persona
  from public.user_personas personas
  where personas.user_id = p_user_id
    and personas.id <> p_persona_id
  order by personas.is_default desc, personas.updated_at desc
  limit 1;

  select count(*)
  into used_in_threads
  from public.chat_threads threads
  where threads.user_id = p_user_id
    and threads.persona_id = p_persona_id;

  if used_in_threads > 0 and replacement_persona.id is null then
    raise exception 'Create another persona before deleting the only persona used by your threads.';
  end if;

  if replacement_persona.id is not null then
    update public.chat_threads
    set
      persona_id = replacement_persona.id,
      updated_at = now()
    where user_id = p_user_id
      and persona_id = p_persona_id;

    if target_persona.is_default then
      update public.user_personas
      set
        is_default = false,
        updated_at = now()
      where user_id = p_user_id
        and is_default = true;

      update public.user_personas
      set
        is_default = true,
        updated_at = now()
      where id = replacement_persona.id
        and user_id = p_user_id;
    end if;
  end if;

  delete from public.user_personas personas
  where personas.id = p_persona_id
    and personas.user_id = p_user_id;

  return replacement_persona.id;
end;
$$;

create or replace function public.upsert_character_bundle(
  p_user_id uuid,
  p_character jsonb,
  p_starters jsonb default '[]'::jsonb,
  p_examples jsonb default '[]'::jsonb
)
returns uuid
language plpgsql
set search_path = public
as $$
declare
  character_id uuid;
  existing_id uuid;
begin
  existing_id := (p_character ->> 'id')::uuid;

  if existing_id is not null then
    if not exists (
      select 1 from public.characters c
      where c.id = existing_id and c.user_id = p_user_id
    ) then
      raise exception 'Character % not found for user %', existing_id, p_user_id;
    end if;

    update public.characters set
      name = coalesce(p_character ->> 'name', name),
      story = coalesce(p_character ->> 'story', story),
      core_persona = coalesce(p_character ->> 'core_persona', core_persona),
      greeting = coalesce(p_character ->> 'greeting', greeting),
      appearance = coalesce(p_character ->> 'appearance', appearance),
      style_rules = coalesce(p_character ->> 'style_rules', style_rules),
      definition = coalesce(p_character ->> 'definition', definition),
      negative_guidance = coalesce(p_character ->> 'negative_guidance', negative_guidance),
      portrait_status = coalesce(p_character ->> 'portrait_status', portrait_status),
      portrait_path = coalesce(p_character ->> 'portrait_path', portrait_path),
      portrait_prompt = coalesce(p_character ->> 'portrait_prompt', portrait_prompt),
      portrait_seed = (p_character ->> 'portrait_seed')::integer,
      portrait_source_hash = coalesce(p_character ->> 'portrait_source_hash', portrait_source_hash),
      portrait_last_error = coalesce(p_character ->> 'portrait_last_error', portrait_last_error),
      portrait_generated_at = (p_character ->> 'portrait_generated_at')::timestamptz,
      temperature = coalesce((p_character ->> 'temperature')::numeric, temperature),
      top_p = coalesce((p_character ->> 'top_p')::numeric, top_p),
      max_output_tokens = coalesce((p_character ->> 'max_output_tokens')::integer, max_output_tokens),
      updated_at = now()
    where id = existing_id and user_id = p_user_id;

    character_id := existing_id;
  else
    insert into public.characters (
      user_id, name, story, core_persona, greeting, appearance,
      style_rules, definition, negative_guidance,
      portrait_status, portrait_path, portrait_prompt, portrait_seed,
      portrait_source_hash, portrait_last_error, portrait_generated_at,
      temperature, top_p, max_output_tokens
    ) values (
      p_user_id,
      coalesce(p_character ->> 'name', ''),
      coalesce(p_character ->> 'story', ''),
      coalesce(p_character ->> 'core_persona', ''),
      coalesce(p_character ->> 'greeting', ''),
      coalesce(p_character ->> 'appearance', ''),
      coalesce(p_character ->> 'style_rules', ''),
      coalesce(p_character ->> 'definition', ''),
      coalesce(p_character ->> 'negative_guidance', ''),
      coalesce(p_character ->> 'portrait_status', 'idle'),
      coalesce(p_character ->> 'portrait_path', ''),
      coalesce(p_character ->> 'portrait_prompt', ''),
      (p_character ->> 'portrait_seed')::integer,
      coalesce(p_character ->> 'portrait_source_hash', ''),
      coalesce(p_character ->> 'portrait_last_error', ''),
      (p_character ->> 'portrait_generated_at')::timestamptz,
      coalesce((p_character ->> 'temperature')::numeric, 0.92),
      coalesce((p_character ->> 'top_p')::numeric, 0.94),
      coalesce((p_character ->> 'max_output_tokens')::integer, 750)
    )
    returning id into character_id;
  end if;

  -- Atomically replace starters
  delete from public.character_starters where character_id = character_id;
  insert into public.character_starters (character_id, text, sort_order)
  select character_id, s.value ->> 'text', (s.ordinality - 1)::integer
  from jsonb_array_elements(p_starters) with ordinality as s(value, ordinality)
  where nullif(trim(s.value ->> 'text'), '') is not null;

  -- Atomically replace examples
  delete from public.character_example_conversations where character_id = character_id;
  insert into public.character_example_conversations (character_id, user_line, character_line, sort_order)
  select character_id, coalesce(e.value ->> 'user_line', ''), coalesce(e.value ->> 'character_line', ''), (e.ordinality - 1)::integer
  from jsonb_array_elements(p_examples) with ordinality as e(value, ordinality)
  where nullif(trim(coalesce(e.value ->> 'user_line', '')), '') is not null
     or nullif(trim(coalesce(e.value ->> 'character_line', '')), '') is not null;

  return character_id;
end;
$$;

create or replace function public.create_thread_with_main_branch(
  p_user_id uuid,
  p_character_id uuid,
  p_connection_id uuid,
  p_model_id text,
  p_persona_id uuid,
  p_title text
)
returns public.chat_threads
language plpgsql
set search_path = public
as $$
declare
  created_thread public.chat_threads;
  created_branch public.chat_branches;
begin
  -- Validate that referenced records belong to the calling user
  if not exists (
    select 1
    from public.characters characters
    where characters.id = p_character_id
      and characters.user_id = p_user_id
  ) then
    raise exception 'Character % not found for user %', p_character_id, p_user_id;
  end if;

  if not exists (
    select 1
    from public.ai_connections connections
    where connections.id = p_connection_id
      and connections.user_id = p_user_id
  ) then
    raise exception 'Connection % not found for user %', p_connection_id, p_user_id;
  end if;

  if p_persona_id is not null and not exists (
    select 1
    from public.user_personas personas
    where personas.id = p_persona_id
      and personas.user_id = p_user_id
  ) then
    raise exception 'Persona % not found for user %', p_persona_id, p_user_id;
  end if;

  insert into public.chat_threads (
    user_id,
    character_id,
    connection_id,
    model_id,
    persona_id,
    title,
    is_title_autogenerated
  )
  values (
    p_user_id,
    p_character_id,
    p_connection_id,
    p_model_id,
    p_persona_id,
    p_title,
    true
  )
  returning * into created_thread;

  insert into public.chat_branches (
    thread_id,
    name,
    created_by
  )
  values (
    created_thread.id,
    'main',
    p_user_id
  )
  returning * into created_branch;

  update public.chat_threads
  set
    active_branch_id = created_branch.id,
    updated_at = now()
  where id = created_thread.id
  returning * into created_thread;

  return created_thread;
end;
$$;

create or replace function public.finalize_turn_and_enqueue_reconcile(
  p_thread_id uuid,
  p_user_id uuid,
  p_branch_id uuid,
  p_parent_checkpoint_id uuid,
  p_choice_group_key text,
  p_user_message_id text,
  p_user_message_parts jsonb,
  p_user_message_content_text text,
  p_user_message_metadata jsonb,
  p_assistant_message_id text,
  p_assistant_message_parts jsonb,
  p_assistant_message_content_text text,
  p_assistant_message_metadata jsonb,
  p_reconcile_payload jsonb,
  p_autotitle_text text default null
)
returns public.chat_checkpoints
language plpgsql
set search_path = public
as $$
declare
  created_checkpoint public.chat_checkpoints;
  next_title text;
begin
  if not exists (
    select 1
    from public.chat_threads threads
    where threads.id = p_thread_id
      and threads.user_id = p_user_id
  ) then
    raise exception 'Thread % not found for user %', p_thread_id, p_user_id;
  end if;

  if not exists (
    select 1
    from public.chat_branches branches
    where branches.id = p_branch_id
      and branches.thread_id = p_thread_id
  ) then
    raise exception 'Branch % not found for thread %', p_branch_id, p_thread_id;
  end if;

  -- Server always generates fresh IDs, so conflicts indicate a UUID collision.
  -- Use DO NOTHING to prevent overwriting historical messages.
  insert into public.chat_messages (
    id,
    thread_id,
    role,
    parts,
    content_text,
    metadata
  )
  values (
    p_user_message_id,
    p_thread_id,
    'user',
    coalesce(p_user_message_parts, '[]'::jsonb),
    coalesce(p_user_message_content_text, ''),
    coalesce(p_user_message_metadata, '{}'::jsonb)
  )
  on conflict (id) do nothing;

  if not found then
    raise exception 'User message id % conflicts with an existing message', p_user_message_id;
  end if;

  insert into public.chat_messages (
    id,
    thread_id,
    role,
    parts,
    content_text,
    metadata
  )
  values (
    p_assistant_message_id,
    p_thread_id,
    'assistant',
    coalesce(p_assistant_message_parts, '[]'::jsonb),
    coalesce(p_assistant_message_content_text, ''),
    coalesce(p_assistant_message_metadata, '{}'::jsonb)
  )
  on conflict (id) do nothing;

  if not found then
    raise exception 'Assistant message id % conflicts with an existing message', p_assistant_message_id;
  end if;

  insert into public.chat_checkpoints (
    thread_id,
    branch_id,
    parent_checkpoint_id,
    user_message_id,
    assistant_message_id,
    choice_group_key,
    feedback_rating,
    created_by
  )
  values (
    p_thread_id,
    p_branch_id,
    p_parent_checkpoint_id,
    p_user_message_id,
    p_assistant_message_id,
    p_choice_group_key,
    null,
    p_user_id
  )
  returning * into created_checkpoint;

  update public.chat_branches
  set
    head_checkpoint_id = created_checkpoint.id,
    updated_at = now()
  where id = p_branch_id
    and thread_id = p_thread_id;

  next_title := nullif(left(trim(coalesce(p_autotitle_text, '')), 60), '');
  if next_title is not null then
    update public.chat_threads
    set
      title = next_title,
      is_title_autogenerated = false,
      updated_at = now()
    where id = p_thread_id
      and user_id = p_user_id
      and is_title_autogenerated = true;
  end if;

  delete from public.background_jobs jobs
  where jobs.type = 'reconcile_checkpoint'
    and jobs.checkpoint_id = created_checkpoint.id;

  insert into public.background_jobs (
    type,
    status,
    user_id,
    thread_id,
    branch_id,
    checkpoint_id,
    payload
  )
  values (
    'reconcile_checkpoint',
    'pending',
    p_user_id,
    p_thread_id,
    p_branch_id,
    created_checkpoint.id,
    jsonb_set(
      coalesce(p_reconcile_payload, '{}'::jsonb),
      '{checkpointId}',
      to_jsonb(created_checkpoint.id::text),
      true
    )
  );

  return created_checkpoint;
end;
$$;

create or replace function public.rewrite_latest_turn_in_place(
  p_thread_id uuid,
  p_user_id uuid,
  p_branch_id uuid,
  p_checkpoint_id uuid,
  p_user_message_id text,
  p_user_message_parts jsonb,
  p_user_message_content_text text,
  p_user_message_metadata jsonb,
  p_assistant_message_id text,
  p_assistant_message_parts jsonb,
  p_assistant_message_content_text text,
  p_assistant_message_metadata jsonb,
  p_reconcile_payload jsonb,
  p_autotitle_text text default null
)
returns public.chat_checkpoints
language plpgsql
set search_path = public
as $$
declare
  existing_checkpoint public.chat_checkpoints;
  next_title text;
begin
  select *
  into existing_checkpoint
  from public.chat_checkpoints checkpoints
  where checkpoints.id = p_checkpoint_id
    and checkpoints.thread_id = p_thread_id
    and checkpoints.branch_id = p_branch_id;

  if existing_checkpoint.id is null then
    raise exception 'Checkpoint % not found on branch %', p_checkpoint_id, p_branch_id;
  end if;

  if not exists (
    select 1
    from public.chat_threads threads
    where threads.id = p_thread_id
      and threads.user_id = p_user_id
  ) then
    raise exception 'Thread % not found for user %', p_thread_id, p_user_id;
  end if;

  if p_user_message_id is not null and p_user_message_id <> existing_checkpoint.user_message_id then
    raise exception 'User message id mismatch for checkpoint %', p_checkpoint_id;
  end if;

  if p_assistant_message_id <> existing_checkpoint.assistant_message_id then
    raise exception 'Assistant message id mismatch for checkpoint %', p_checkpoint_id;
  end if;

  if p_user_message_id is not null then
    update public.chat_messages
    set
      parts = coalesce(p_user_message_parts, parts),
      content_text = coalesce(p_user_message_content_text, content_text),
      metadata = coalesce(p_user_message_metadata, metadata)
    where id = existing_checkpoint.user_message_id
      and thread_id = p_thread_id;
  end if;

  update public.chat_messages
  set
    parts = coalesce(p_assistant_message_parts, parts),
    content_text = coalesce(p_assistant_message_content_text, content_text),
    metadata = coalesce(p_assistant_message_metadata, metadata)
  where id = existing_checkpoint.assistant_message_id
    and thread_id = p_thread_id;

  delete from public.chat_state_snapshots
  where checkpoint_id = existing_checkpoint.id;

  delete from public.chat_timeline_events events
  where events.checkpoint_id = existing_checkpoint.id
     or events.source_message_id = existing_checkpoint.assistant_message_id;

  delete from public.background_jobs jobs
  where jobs.type = 'reconcile_checkpoint'
    and jobs.checkpoint_id = existing_checkpoint.id;

  update public.chat_checkpoints
  set feedback_rating = null
  where id = existing_checkpoint.id;

  update public.chat_branches
  set
    head_checkpoint_id = existing_checkpoint.id,
    updated_at = now()
  where id = p_branch_id
    and thread_id = p_thread_id;

  next_title := nullif(left(trim(coalesce(p_autotitle_text, '')), 60), '');
  if next_title is not null then
    update public.chat_threads
    set
      title = next_title,
      is_title_autogenerated = false,
      updated_at = now()
    where id = p_thread_id
      and user_id = p_user_id
      and is_title_autogenerated = true;
  end if;

  insert into public.background_jobs (
    type,
    status,
    user_id,
    thread_id,
    branch_id,
    checkpoint_id,
    payload
  )
  values (
    'reconcile_checkpoint',
    'pending',
    p_user_id,
    p_thread_id,
    p_branch_id,
    existing_checkpoint.id,
    coalesce(p_reconcile_payload, '{}'::jsonb)
  );

  select *
  into existing_checkpoint
  from public.chat_checkpoints checkpoints
  where checkpoints.id = p_checkpoint_id;

  return existing_checkpoint;
end;
$$;

create or replace function public.rewind_thread_to_checkpoint(
  p_thread_id uuid,
  p_user_id uuid,
  p_branch_id uuid,
  p_checkpoint_id uuid
)
returns uuid
language plpgsql
set search_path = public
as $$
declare
  selected_checkpoint public.chat_checkpoints;
  selected_created_at timestamptz;
  descendant_checkpoint_ids uuid[] := array[]::uuid[];
  descendant_branch_ids uuid[] := array[]::uuid[];
  descendant_message_ids text[] := array[]::text[];
begin
  if not exists (
    select 1
    from public.chat_threads threads
    where threads.id = p_thread_id
      and threads.user_id = p_user_id
  ) then
    raise exception 'Thread % not found for user %', p_thread_id, p_user_id;
  end if;

  select *
  into selected_checkpoint
  from public.chat_checkpoints checkpoints
  where checkpoints.id = p_checkpoint_id
    and checkpoints.thread_id = p_thread_id
    and checkpoints.branch_id = p_branch_id;

  if selected_checkpoint.id is null then
    raise exception 'Checkpoint % not found on branch %', p_checkpoint_id, p_branch_id;
  end if;

  selected_created_at := selected_checkpoint.created_at;

  with recursive checkpoint_tree as (
    select checkpoints.id
    from public.chat_checkpoints checkpoints
    where checkpoints.thread_id = p_thread_id
      and checkpoints.parent_checkpoint_id = p_checkpoint_id
    union all
    select checkpoints.id
    from public.chat_checkpoints checkpoints
    inner join checkpoint_tree tree
      on checkpoints.parent_checkpoint_id = tree.id
    where checkpoints.thread_id = p_thread_id
  )
  select coalesce(array_agg(tree.id), array[]::uuid[])
  into descendant_checkpoint_ids
  from checkpoint_tree tree;

  with recursive branch_tree as (
    select branches.id
    from public.chat_branches branches
    where branches.thread_id = p_thread_id
      and branches.id <> p_branch_id
      and (
        branches.fork_checkpoint_id = p_checkpoint_id
        or branches.fork_checkpoint_id = any(descendant_checkpoint_ids)
      )
    union all
    select branches.id
    from public.chat_branches branches
    inner join branch_tree tree
      on branches.parent_branch_id = tree.id
    where branches.thread_id = p_thread_id
      and branches.id <> p_branch_id
  )
  select coalesce(array_agg(tree.id), array[]::uuid[])
  into descendant_branch_ids
  from branch_tree tree;

  select coalesce(array_agg(distinct message_id), array[]::text[])
  into descendant_message_ids
  from (
    select checkpoints.user_message_id as message_id
    from public.chat_checkpoints checkpoints
    where checkpoints.id = any(descendant_checkpoint_ids)
    union all
    select checkpoints.assistant_message_id as message_id
    from public.chat_checkpoints checkpoints
    where checkpoints.id = any(descendant_checkpoint_ids)
  ) descendant_messages;

  delete from public.background_jobs jobs
  where jobs.thread_id = p_thread_id
    and (
      jobs.branch_id = any(descendant_branch_ids)
      or jobs.checkpoint_id = any(descendant_checkpoint_ids)
      or (jobs.branch_id = p_branch_id and jobs.created_at > selected_created_at)
    );

  delete from public.chat_pins pins
  where pins.thread_id = p_thread_id
    and (
      pins.branch_id = any(descendant_branch_ids)
      or pins.source_message_id = any(descendant_message_ids)
      or (pins.branch_id = p_branch_id and pins.created_at > selected_created_at)
    );

  delete from public.chat_timeline_events events
  where events.thread_id = p_thread_id
    and (
      events.branch_id = any(descendant_branch_ids)
      or events.checkpoint_id = any(descendant_checkpoint_ids)
      or events.source_message_id = any(descendant_message_ids)
      or (events.branch_id = p_branch_id and events.created_at > selected_created_at)
    );

  delete from public.chat_state_snapshots snapshots
  where snapshots.checkpoint_id = any(descendant_checkpoint_ids);

  delete from public.chat_branches branches
  where branches.id = any(descendant_branch_ids);

  delete from public.chat_checkpoints checkpoints
  where checkpoints.id = any(descendant_checkpoint_ids);

  delete from public.chat_messages messages
  where messages.id = any(descendant_message_ids);

  update public.chat_branches
  set
    head_checkpoint_id = p_checkpoint_id,
    updated_at = now()
  where id = p_branch_id
    and thread_id = p_thread_id;

  return p_checkpoint_id;
end;
$$;


create or replace function public.get_thread_graph_payload(
  p_user_id uuid,
  p_thread_id uuid
)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
  owned_thread public.chat_threads;
  active_branch public.chat_branches;
begin
  select *
  into owned_thread
  from public.chat_threads threads
  where threads.id = p_thread_id
    and threads.user_id = p_user_id;

  if owned_thread.id is null or owned_thread.active_branch_id is null then
    return null;
  end if;

  select *
  into active_branch
  from public.chat_branches branches
  where branches.id = owned_thread.active_branch_id
    and branches.thread_id = p_thread_id;

  if active_branch.id is null then
    return null;
  end if;

  return (
    with recursive checkpoint_path as (
      select
        checkpoints.id,
        checkpoints.thread_id,
        checkpoints.branch_id,
        checkpoints.parent_checkpoint_id,
        checkpoints.user_message_id,
        checkpoints.assistant_message_id,
        checkpoints.choice_group_key,
        checkpoints.feedback_rating,
        checkpoints.created_by,
        checkpoints.created_at,
        0 as depth
      from public.chat_checkpoints checkpoints
      where checkpoints.id = active_branch.head_checkpoint_id

      union all

      select
        parent.id,
        parent.thread_id,
        parent.branch_id,
        parent.parent_checkpoint_id,
        parent.user_message_id,
        parent.assistant_message_id,
        parent.choice_group_key,
        parent.feedback_rating,
        parent.created_by,
        parent.created_at,
        child.depth + 1
      from public.chat_checkpoints parent
      inner join checkpoint_path child
        on child.parent_checkpoint_id = parent.id
      where parent.thread_id = p_thread_id
    ),
    ordered_checkpoints as (
      select
        id,
        thread_id,
        branch_id,
        parent_checkpoint_id,
        user_message_id,
        assistant_message_id,
        choice_group_key,
        feedback_rating,
        created_by,
        created_at,
        depth
      from checkpoint_path
      order by depth desc
    ),
    checkpoint_ids as (
      select coalesce(array_agg(checkpoints.id), array[]::uuid[]) as value
      from ordered_checkpoints checkpoints
    ),
    message_ids as (
      select coalesce(array_agg(distinct ids.message_id), array[]::text[]) as value
      from (
        select checkpoints.user_message_id as message_id
        from ordered_checkpoints checkpoints
        union
        select checkpoints.assistant_message_id as message_id
        from ordered_checkpoints checkpoints
      ) ids
    ),
    message_rows as (
      select
        messages.id,
        messages.thread_id,
        messages.role,
        messages.parts,
        messages.content_text,
        messages.metadata,
        messages.created_at
      from public.chat_messages messages
      where messages.id = any(
        coalesce((select value from message_ids), array[]::text[])
      )
    ),
    snapshot_rows as (
      select
        snapshots.checkpoint_id,
        snapshots.thread_id,
        snapshots.branch_id,
        snapshots.based_on_snapshot_id,
        snapshots.scenario_state,
        snapshots.relationship_state,
        snapshots.rolling_summary,
        snapshots.user_facts,
        snapshots.open_loops,
        snapshots.resolved_loops,
        snapshots.narrative_hooks,
        snapshots.scene_goals,
        snapshots.version,
        snapshots.updated_at
      from public.chat_state_snapshots snapshots
      where snapshots.checkpoint_id = any(
        coalesce((select value from checkpoint_ids), array[]::uuid[])
      )
    ),
    timeline_rows as (
      select
        events.id,
        events.thread_id,
        events.branch_id,
        events.checkpoint_id,
        events.source_message_id,
        events.title,
        events.detail,
        events.importance,
        events.created_at
      from public.chat_timeline_events events
      where events.thread_id = p_thread_id
        and events.branch_id = active_branch.id
      order by events.created_at desc
      limit 24
    ),
    pin_rows as (
      select
        pins.id,
        pins.thread_id,
        pins.branch_id,
        pins.source_message_id,
        pins.body,
        pins.status,
        pins.created_at,
        pins.updated_at
      from public.chat_pins pins
      where pins.thread_id = p_thread_id
        and pins.branch_id = active_branch.id
        and pins.status = 'active'
      order by pins.created_at desc
    ),
    latest_reconcile_job as (
      select
        jobs.id,
        jobs.type,
        jobs.status,
        jobs.user_id,
        jobs.thread_id,
        jobs.branch_id,
        jobs.checkpoint_id,
        jobs.payload,
        jobs.attempts,
        jobs.max_attempts,
        jobs.available_at,
        jobs.locked_at,
        jobs.last_error,
        jobs.created_at,
        jobs.updated_at
      from public.background_jobs jobs
      where jobs.type = 'reconcile_checkpoint'
        and jobs.checkpoint_id = active_branch.head_checkpoint_id
      order by jobs.created_at desc
      limit 1
    )
    select jsonb_build_object(
      'thread',
      to_jsonb(owned_thread),
      'activeBranch',
      to_jsonb(active_branch),
      'branches',
      coalesce(
        (
          select jsonb_agg(to_jsonb(branches) order by branches.created_at)
          from public.chat_branches branches
          where branches.thread_id = p_thread_id
        ),
        '[]'::jsonb
      ),
      'checkpoints',
      coalesce(
        (
          select jsonb_agg(
            to_jsonb(checkpoints) - 'depth'
            order by checkpoints.depth desc
          )
          from ordered_checkpoints checkpoints
        ),
        '[]'::jsonb
      ),
      'messages',
      coalesce(
        (
          select jsonb_agg(to_jsonb(messages))
          from message_rows messages
        ),
        '[]'::jsonb
      ),
      'snapshots',
      coalesce(
        (
          select jsonb_agg(to_jsonb(snapshots))
          from snapshot_rows snapshots
        ),
        '[]'::jsonb
      ),
      'timeline',
      coalesce(
        (
          select jsonb_agg(to_jsonb(events) order by events.created_at desc)
          from timeline_rows events
        ),
        '[]'::jsonb
      ),
      'pins',
      coalesce(
        (
          select jsonb_agg(to_jsonb(pins) order by pins.created_at desc)
          from pin_rows pins
        ),
        '[]'::jsonb
      ),
      'latestReconcileJob',
      (
        select to_jsonb(jobs)
        from latest_reconcile_job jobs
      )
    )
  );
end;
$$;
