create or replace function public.set_default_persona(
  target_persona_id uuid,
  target_user_id uuid
)
returns setof public.user_personas
language plpgsql
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.user_personas personas
    where personas.id = target_persona_id
      and personas.user_id = target_user_id
  ) then
    raise exception 'Persona % not found for user %', target_persona_id, target_user_id;
  end if;

  update public.user_personas
  set
    is_default = (id = target_persona_id),
    updated_at = now()
  where user_id = target_user_id
    and (is_default = true or id = target_persona_id);

  return query
  select *
  from public.user_personas personas
  where personas.user_id = target_user_id
  order by personas.is_default desc, personas.updated_at desc;
end;
$$;

create or replace function public.create_thread_with_main_branch(
  p_user_id uuid,
  p_character_id uuid,
  p_connection_id uuid,
  p_model_id text,
  p_persona_id uuid,
  p_title text
)
returns public.chat_threads
language plpgsql
set search_path = public
as $$
declare
  created_thread public.chat_threads;
  created_branch public.chat_branches;
begin
  insert into public.chat_threads (
    user_id,
    character_id,
    connection_id,
    model_id,
    persona_id,
    title,
    is_title_autogenerated
  )
  values (
    p_user_id,
    p_character_id,
    p_connection_id,
    p_model_id,
    p_persona_id,
    p_title,
    true
  )
  returning * into created_thread;

  insert into public.chat_branches (
    thread_id,
    name,
    created_by
  )
  values (
    created_thread.id,
    'main',
    p_user_id
  )
  returning * into created_branch;

  update public.chat_threads
  set
    active_branch_id = created_branch.id,
    updated_at = now()
  where id = created_thread.id
  returning * into created_thread;

  return created_thread;
end;
$$;

create or replace function public.finalize_turn_and_enqueue_reconcile(
  p_thread_id uuid,
  p_user_id uuid,
  p_branch_id uuid,
  p_parent_checkpoint_id uuid,
  p_choice_group_key text,
  p_user_message_id text,
  p_user_message_parts jsonb,
  p_user_message_content_text text,
  p_user_message_metadata jsonb,
  p_assistant_message_id text,
  p_assistant_message_parts jsonb,
  p_assistant_message_content_text text,
  p_assistant_message_metadata jsonb,
  p_reconcile_payload jsonb,
  p_autotitle_text text default null
)
returns public.chat_checkpoints
language plpgsql
set search_path = public
as $$
declare
  created_checkpoint public.chat_checkpoints;
  next_title text;
begin
  if not exists (
    select 1
    from public.chat_threads threads
    where threads.id = p_thread_id
      and threads.user_id = p_user_id
  ) then
    raise exception 'Thread % not found for user %', p_thread_id, p_user_id;
  end if;

  if not exists (
    select 1
    from public.chat_branches branches
    where branches.id = p_branch_id
      and branches.thread_id = p_thread_id
  ) then
    raise exception 'Branch % not found for thread %', p_branch_id, p_thread_id;
  end if;

  insert into public.chat_messages (
    id,
    thread_id,
    role,
    parts,
    content_text,
    metadata
  )
  values (
    p_user_message_id,
    p_thread_id,
    'user',
    coalesce(p_user_message_parts, '[]'::jsonb),
    coalesce(p_user_message_content_text, ''),
    coalesce(p_user_message_metadata, '{}'::jsonb)
  )
  on conflict (id) do update
  set
    thread_id = excluded.thread_id,
    role = excluded.role,
    parts = excluded.parts,
    content_text = excluded.content_text,
    metadata = excluded.metadata;

  insert into public.chat_messages (
    id,
    thread_id,
    role,
    parts,
    content_text,
    metadata
  )
  values (
    p_assistant_message_id,
    p_thread_id,
    'assistant',
    coalesce(p_assistant_message_parts, '[]'::jsonb),
    coalesce(p_assistant_message_content_text, ''),
    coalesce(p_assistant_message_metadata, '{}'::jsonb)
  )
  on conflict (id) do update
  set
    thread_id = excluded.thread_id,
    role = excluded.role,
    parts = excluded.parts,
    content_text = excluded.content_text,
    metadata = excluded.metadata;

  insert into public.chat_checkpoints (
    thread_id,
    branch_id,
    parent_checkpoint_id,
    user_message_id,
    assistant_message_id,
    choice_group_key,
    feedback_rating,
    created_by
  )
  values (
    p_thread_id,
    p_branch_id,
    p_parent_checkpoint_id,
    p_user_message_id,
    p_assistant_message_id,
    p_choice_group_key,
    null,
    p_user_id
  )
  returning * into created_checkpoint;

  update public.chat_branches
  set
    head_checkpoint_id = created_checkpoint.id,
    updated_at = now()
  where id = p_branch_id
    and thread_id = p_thread_id;

  next_title := nullif(left(trim(coalesce(p_autotitle_text, '')), 60), '');
  if next_title is not null then
    update public.chat_threads
    set
      title = next_title,
      is_title_autogenerated = false,
      updated_at = now()
    where id = p_thread_id
      and user_id = p_user_id
      and is_title_autogenerated = true;
  end if;

  delete from public.background_jobs jobs
  where jobs.type = 'reconcile_checkpoint'
    and jobs.checkpoint_id = created_checkpoint.id;

  insert into public.background_jobs (
    type,
    status,
    user_id,
    thread_id,
    branch_id,
    checkpoint_id,
    payload
  )
  values (
    'reconcile_checkpoint',
    'pending',
    p_user_id,
    p_thread_id,
    p_branch_id,
    created_checkpoint.id,
    jsonb_set(
      coalesce(p_reconcile_payload, '{}'::jsonb),
      '{checkpointId}',
      to_jsonb(created_checkpoint.id::text),
      true
    )
  );

  return created_checkpoint;
end;
$$;

create or replace function public.rewrite_latest_turn_in_place(
  p_thread_id uuid,
  p_user_id uuid,
  p_branch_id uuid,
  p_checkpoint_id uuid,
  p_user_message_id text,
  p_user_message_parts jsonb,
  p_user_message_content_text text,
  p_user_message_metadata jsonb,
  p_assistant_message_id text,
  p_assistant_message_parts jsonb,
  p_assistant_message_content_text text,
  p_assistant_message_metadata jsonb,
  p_reconcile_payload jsonb,
  p_autotitle_text text default null
)
returns public.chat_checkpoints
language plpgsql
set search_path = public
as $$
declare
  existing_checkpoint public.chat_checkpoints;
  next_title text;
begin
  select *
  into existing_checkpoint
  from public.chat_checkpoints checkpoints
  where checkpoints.id = p_checkpoint_id
    and checkpoints.thread_id = p_thread_id
    and checkpoints.branch_id = p_branch_id;

  if existing_checkpoint.id is null then
    raise exception 'Checkpoint % not found on branch %', p_checkpoint_id, p_branch_id;
  end if;

  if not exists (
    select 1
    from public.chat_threads threads
    where threads.id = p_thread_id
      and threads.user_id = p_user_id
  ) then
    raise exception 'Thread % not found for user %', p_thread_id, p_user_id;
  end if;

  if p_user_message_id is not null and p_user_message_id <> existing_checkpoint.user_message_id then
    raise exception 'User message id mismatch for checkpoint %', p_checkpoint_id;
  end if;

  if p_assistant_message_id <> existing_checkpoint.assistant_message_id then
    raise exception 'Assistant message id mismatch for checkpoint %', p_checkpoint_id;
  end if;

  if p_user_message_id is not null then
    update public.chat_messages
    set
      parts = coalesce(p_user_message_parts, parts),
      content_text = coalesce(p_user_message_content_text, content_text),
      metadata = coalesce(p_user_message_metadata, metadata)
    where id = existing_checkpoint.user_message_id
      and thread_id = p_thread_id;
  end if;

  update public.chat_messages
  set
    parts = coalesce(p_assistant_message_parts, parts),
    content_text = coalesce(p_assistant_message_content_text, content_text),
    metadata = coalesce(p_assistant_message_metadata, metadata)
  where id = existing_checkpoint.assistant_message_id
    and thread_id = p_thread_id;

  delete from public.chat_state_snapshots
  where checkpoint_id = existing_checkpoint.id;

  delete from public.chat_timeline_events events
  where events.checkpoint_id = existing_checkpoint.id
     or events.source_message_id = existing_checkpoint.assistant_message_id;

  delete from public.background_jobs jobs
  where jobs.type = 'reconcile_checkpoint'
    and jobs.checkpoint_id = existing_checkpoint.id;

  update public.chat_checkpoints
  set feedback_rating = null
  where id = existing_checkpoint.id;

  update public.chat_branches
  set
    head_checkpoint_id = existing_checkpoint.id,
    updated_at = now()
  where id = p_branch_id
    and thread_id = p_thread_id;

  next_title := nullif(left(trim(coalesce(p_autotitle_text, '')), 60), '');
  if next_title is not null then
    update public.chat_threads
    set
      title = next_title,
      is_title_autogenerated = false,
      updated_at = now()
    where id = p_thread_id
      and user_id = p_user_id
      and is_title_autogenerated = true;
  end if;

  insert into public.background_jobs (
    type,
    status,
    user_id,
    thread_id,
    branch_id,
    checkpoint_id,
    payload
  )
  values (
    'reconcile_checkpoint',
    'pending',
    p_user_id,
    p_thread_id,
    p_branch_id,
    existing_checkpoint.id,
    coalesce(p_reconcile_payload, '{}'::jsonb)
  );

  select *
  into existing_checkpoint
  from public.chat_checkpoints checkpoints
  where checkpoints.id = p_checkpoint_id;

  return existing_checkpoint;
end;
$$;

create or replace function public.rewind_thread_to_checkpoint(
  p_thread_id uuid,
  p_user_id uuid,
  p_branch_id uuid,
  p_checkpoint_id uuid
)
returns uuid
language plpgsql
set search_path = public
as $$
declare
  selected_checkpoint public.chat_checkpoints;
  selected_created_at timestamptz;
  descendant_checkpoint_ids uuid[] := array[]::uuid[];
  descendant_branch_ids uuid[] := array[]::uuid[];
  descendant_message_ids text[] := array[]::text[];
begin
  if not exists (
    select 1
    from public.chat_threads threads
    where threads.id = p_thread_id
      and threads.user_id = p_user_id
  ) then
    raise exception 'Thread % not found for user %', p_thread_id, p_user_id;
  end if;

  select *
  into selected_checkpoint
  from public.chat_checkpoints checkpoints
  where checkpoints.id = p_checkpoint_id
    and checkpoints.thread_id = p_thread_id
    and checkpoints.branch_id = p_branch_id;

  if selected_checkpoint.id is null then
    raise exception 'Checkpoint % not found on branch %', p_checkpoint_id, p_branch_id;
  end if;

  selected_created_at := selected_checkpoint.created_at;

  with recursive checkpoint_tree as (
    select checkpoints.id
    from public.chat_checkpoints checkpoints
    where checkpoints.thread_id = p_thread_id
      and checkpoints.parent_checkpoint_id = p_checkpoint_id
    union all
    select checkpoints.id
    from public.chat_checkpoints checkpoints
    inner join checkpoint_tree tree
      on checkpoints.parent_checkpoint_id = tree.id
    where checkpoints.thread_id = p_thread_id
  )
  select coalesce(array_agg(tree.id), array[]::uuid[])
  into descendant_checkpoint_ids
  from checkpoint_tree tree;

  with recursive branch_tree as (
    select branches.id
    from public.chat_branches branches
    where branches.thread_id = p_thread_id
      and branches.id <> p_branch_id
      and (
        branches.fork_checkpoint_id = p_checkpoint_id
        or branches.fork_checkpoint_id = any(descendant_checkpoint_ids)
      )
    union all
    select branches.id
    from public.chat_branches branches
    inner join branch_tree tree
      on branches.parent_branch_id = tree.id
    where branches.thread_id = p_thread_id
      and branches.id <> p_branch_id
  )
  select coalesce(array_agg(tree.id), array[]::uuid[])
  into descendant_branch_ids
  from branch_tree tree;

  select coalesce(array_agg(distinct message_id), array[]::text[])
  into descendant_message_ids
  from (
    select checkpoints.user_message_id as message_id
    from public.chat_checkpoints checkpoints
    where checkpoints.id = any(descendant_checkpoint_ids)
    union all
    select checkpoints.assistant_message_id as message_id
    from public.chat_checkpoints checkpoints
    where checkpoints.id = any(descendant_checkpoint_ids)
  ) descendant_messages;

  delete from public.background_jobs jobs
  where jobs.thread_id = p_thread_id
    and (
      jobs.branch_id = any(descendant_branch_ids)
      or jobs.checkpoint_id = any(descendant_checkpoint_ids)
      or (jobs.branch_id = p_branch_id and jobs.created_at > selected_created_at)
    );

  delete from public.chat_pins pins
  where pins.thread_id = p_thread_id
    and (
      pins.branch_id = any(descendant_branch_ids)
      or pins.source_message_id = any(descendant_message_ids)
      or (pins.branch_id = p_branch_id and pins.created_at > selected_created_at)
    );

  delete from public.chat_timeline_events events
  where events.thread_id = p_thread_id
    and (
      events.branch_id = any(descendant_branch_ids)
      or events.checkpoint_id = any(descendant_checkpoint_ids)
      or events.source_message_id = any(descendant_message_ids)
      or (events.branch_id = p_branch_id and events.created_at > selected_created_at)
    );

  delete from public.chat_state_snapshots snapshots
  where snapshots.checkpoint_id = any(descendant_checkpoint_ids);

  delete from public.chat_branches branches
  where branches.id = any(descendant_branch_ids);

  delete from public.chat_checkpoints checkpoints
  where checkpoints.id = any(descendant_checkpoint_ids);

  delete from public.chat_messages messages
  where messages.id = any(descendant_message_ids);

  update public.chat_branches
  set
    head_checkpoint_id = p_checkpoint_id,
    updated_at = now()
  where id = p_branch_id
    and thread_id = p_thread_id;

  return p_checkpoint_id;
end;
$$;
